/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteMantenimientodeMaterias;

import com.inet.jortho.FileUserDictionary;
import com.inet.jortho.SpellChecker;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franciscoantonio
 */
public class InterfazRegistrarMateria extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAltadeMateria
     */
    public InterfazRegistrarMateria() {
        initComponents();

        //verifica la ortografia
        SpellChecker.setUserDictionaryProvider(new FileUserDictionary());
        SpellChecker.registerDictionaries(null, null);
        SpellChecker.register(txt1Materia);

        //establece la posicion central de l ainterfaz
        this.setLocationRelativeTo(null);
        //coloca el icono 3en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        //desactiva la opcion maximizar
        this.setResizable(false);
        //desactiva la opcion cerrar
        setDefaultCloseOperation(0);
        //establece el nombre de administrados en la interfaz
        jMenu1.setText("Mi cuenta: ADMINISTRADOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp3RegistrarMateria = new javax.swing.JPanel();
        boton2Salir = new javax.swing.JButton();
        boton3Cancelar = new javax.swing.JButton();
        boton1Registrar = new javax.swing.JButton();
        jp2TemasMateria = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1Temas = new javax.swing.JTable();
        boton4Agregar = new javax.swing.JButton();
        boton5Remover = new javax.swing.JButton();
        jp1Materia = new javax.swing.JPanel();
        txt1Materia = new javax.swing.JTextField();
        lab1Materia = new javax.swing.JLabel();
        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento materia/Registro de materia");

        jp3RegistrarMateria.setBackground(new java.awt.Color(253, 251, 251));

        boton2Salir.setBackground(new java.awt.Color(255, 255, 255));
        boton2Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2Salir.setText("Salir");
        boton2Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        boton3Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        boton3Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton3Cancelar.setText("Cancelar");
        boton3Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        boton1Registrar.setBackground(new java.awt.Color(51, 204, 0));
        boton1Registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton1Registrar.setText("Registrar");
        boton1Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar(evt);
            }
        });

        jp2TemasMateria.setBackground(new java.awt.Color(253, 251, 251));
        jp2TemasMateria.setBorder(javax.swing.BorderFactory.createTitledBorder("Temas de la materia"));

        Table1Temas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del tema", "Grado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table1Temas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Table1Temas);
        if (Table1Temas.getColumnModel().getColumnCount() > 0) {
            Table1Temas.getColumnModel().getColumn(0).setResizable(false);
            Table1Temas.getColumnModel().getColumn(1).setResizable(false);
        }

        boton4Agregar.setBackground(new java.awt.Color(255, 255, 255));
        boton4Agregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton4Agregar.setText("+");
        boton4Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRenglon(evt);
            }
        });

        boton5Remover.setBackground(new java.awt.Color(255, 255, 255));
        boton5Remover.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton5Remover.setText("-");
        boton5Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerRenglon(evt);
            }
        });

        javax.swing.GroupLayout jp2TemasMateriaLayout = new javax.swing.GroupLayout(jp2TemasMateria);
        jp2TemasMateria.setLayout(jp2TemasMateriaLayout);
        jp2TemasMateriaLayout.setHorizontalGroup(
            jp2TemasMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2TemasMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp2TemasMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2TemasMateriaLayout.createSequentialGroup()
                        .addComponent(boton5Remover)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2TemasMateriaLayout.createSequentialGroup()
                        .addComponent(boton4Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jp2TemasMateriaLayout.setVerticalGroup(
            jp2TemasMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2TemasMateriaLayout.createSequentialGroup()
                .addGroup(jp2TemasMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jp2TemasMateriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2TemasMateriaLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(boton4Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton5Remover)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jp1Materia.setBackground(new java.awt.Color(253, 251, 251));
        jp1Materia.setBorder(javax.swing.BorderFactory.createTitledBorder("Materia a registrar"));

        txt1Materia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt1Materia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                existeMateria(evt);
            }
        });

        lab1Materia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab1Materia.setText("Nombre de la Materia:");

        javax.swing.GroupLayout jp1MateriaLayout = new javax.swing.GroupLayout(jp1Materia);
        jp1Materia.setLayout(jp1MateriaLayout);
        jp1MateriaLayout.setHorizontalGroup(
            jp1MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1MateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab1Materia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt1Materia)
                .addContainerGap())
        );
        jp1MateriaLayout.setVerticalGroup(
            jp1MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1MateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp3RegistrarMateriaLayout = new javax.swing.GroupLayout(jp3RegistrarMateria);
        jp3RegistrarMateria.setLayout(jp3RegistrarMateriaLayout);
        jp3RegistrarMateriaLayout.setHorizontalGroup(
            jp3RegistrarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3RegistrarMateriaLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jp3RegistrarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(boton3Cancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton2Salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton1Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp3RegistrarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jp1Materia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp2TemasMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp3RegistrarMateriaLayout.setVerticalGroup(
            jp3RegistrarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3RegistrarMateriaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jp3RegistrarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3RegistrarMateriaLayout.createSequentialGroup()
                        .addComponent(boton1Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton3Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton2Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp3RegistrarMateriaLayout.createSequentialGroup()
                        .addComponent(jp1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jp2TemasMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu1.setText("Mi cuenta");
        jMenu1.setToolTipText("");
        menu1.add(jMenu1);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp3RegistrarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp3RegistrarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar
        int registrar = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA REGISTRAR LA MATERIA Y LOS TEMAS?");
        if (registrar == 0) {

            ControlMateria cMateria = new ControlMateria();
            try {

                String registrarMateria = cMateria.registrarMateria(txt1Materia.getText(), Table1Temas);
                JOptionPane.showMessageDialog(rootPane, "Materia registrada exitosamente\n" + txt1Materia.getText() + " " + registrarMateria, "Felicidades", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            } catch (ClassNotFoundException | SQLException ex) {
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_registrar

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        limpiarCampos();
    }//GEN-LAST:event_cancelar

    public void limpiarCampos() {
        txt1Materia.setText("");
        DefaultTableModel modelo = (DefaultTableModel) Table1Temas.getModel();
        int total = Table1Temas.getRowCount();
        for (int i = 0; i < total; i++) {
            modelo.removeRow(0);
        }
    }

    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {
            limpiarCampos();
            this.setVisible(false);

        }
    }//GEN-LAST:event_salir

    private void existeMateria(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_existeMateria

        try {
            ControlMateria Cmateria = new ControlMateria();
            //saber si el maestro ya existe
            boolean resultadodeConsultar = Cmateria.existeMateria(txt1Materia.getText());

            if (resultadodeConsultar) {
                JOptionPane.showMessageDialog(rootPane, "LA MATERIA YA EXISTE", "ERROR", JOptionPane.ERROR_MESSAGE);
                txt1Materia.setText("");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("Error con el servidor");
        }

    }//GEN-LAST:event_existeMateria

    private void agregarRenglon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRenglon
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) Table1Temas.getModel();
        modelo.addRow(new Object[]{
            "",
            ""
        });


    }//GEN-LAST:event_agregarRenglon

    private void removerRenglon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerRenglon

        DefaultTableModel modelo = (DefaultTableModel) Table1Temas.getModel();
        try {
            modelo.removeRow(modelo.getRowCount() - 1);
        } catch (ArrayIndexOutOfBoundsException e) {
        }
    }//GEN-LAST:event_removerRenglon

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistrarMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1Temas;
    private javax.swing.JButton boton1Registrar;
    private javax.swing.JButton boton2Salir;
    private javax.swing.JButton boton3Cancelar;
    private javax.swing.JButton boton4Agregar;
    private javax.swing.JButton boton5Remover;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jp1Materia;
    private javax.swing.JPanel jp2TemasMateria;
    private javax.swing.JPanel jp3RegistrarMateria;
    private javax.swing.JLabel lab1Materia;
    private javax.swing.JMenuBar menu1;
    private javax.swing.JTextField txt1Materia;
    // End of variables declaration//GEN-END:variables
}
