/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteMantenimientodeEvaluaciones;

import PaqueteMantenimientodeMaterias.ControlMateria;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazAplicarEvaluacion extends javax.swing.JFrame {

    boolean materiaSeleccionada = false;
    boolean gradoSeleccionado = false;
    String[][] contenedordeReactivos;
    int posicionReactivo = 1;
    int idEvaluacion = 0;
    public int idUsuario;
    public String nombre;

    /**
     * Creates new form InterfazAplicarEvaluacion
     */
    public InterfazAplicarEvaluacion() {
        initComponents();

        //establece la posicion central de la interfaz
        this.setLocationRelativeTo(null);

        //coloca el icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        //desactiva la opcion maximizar
        this.setResizable(false);
        //desactiva la opcion cerrar
        setDefaultCloseOperation(0);
        //desactiva el boton aplicar evaluacion
        boton2AplicarEvaluacion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1AplicarEvaluacion = new javax.swing.JPanel();
        jp2Evaluacion = new javax.swing.JPanel();
        lab1Materia = new javax.swing.JLabel();
        lab2Grado = new javax.swing.JLabel();
        lab3Evaluacion = new javax.swing.JLabel();
        cbox1Materia = new javax.swing.JComboBox();
        cbox2Grado = new javax.swing.JComboBox();
        cbox3Evaluacion = new javax.swing.JComboBox();
        boton2AplicarEvaluacion = new javax.swing.JButton();
        boton4Salir = new javax.swing.JButton();
        jp4Reactivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta1Reactivo = new javax.swing.JTextArea();
        lab6A = new javax.swing.JLabel();
        lab7B = new javax.swing.JLabel();
        lab8C = new javax.swing.JLabel();
        boton5Anterior = new javax.swing.JButton();
        boton6Siguiente = new javax.swing.JButton();
        lab5Reactivos = new javax.swing.JLabel();
        lab9Respuesta1 = new javax.swing.JLabel();
        lab11Respuesta3 = new javax.swing.JLabel();
        lab10Respuesta2 = new javax.swing.JLabel();
        jp3Grupo = new javax.swing.JPanel();
        lab4Grupo = new javax.swing.JLabel();
        cbox4Grupo = new javax.swing.JComboBox();
        boton1VistaPrevia = new javax.swing.JButton();
        boton3Cancelar = new javax.swing.JButton();
        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento de evaluaciones/Aplicar Evaluación");
        setMinimumSize(new java.awt.Dimension(823, 642));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                personalizarInterfaz(evt);
            }
        });

        jp1AplicarEvaluacion.setBackground(new java.awt.Color(245, 245, 239));
        jp1AplicarEvaluacion.setMaximumSize(new java.awt.Dimension(823, 642));
        jp1AplicarEvaluacion.setMinimumSize(new java.awt.Dimension(823, 642));
        jp1AplicarEvaluacion.setPreferredSize(new java.awt.Dimension(823, 642));

        jp2Evaluacion.setBackground(new java.awt.Color(253, 251, 251));
        jp2Evaluacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de la evaluación"));

        lab1Materia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab1Materia.setText("Materia:");

        lab2Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab2Grado.setText("Grado:");

        lab3Evaluacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab3Evaluacion.setText("Evaluación:");

        cbox1Materia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox1Materia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción", "Matemáticas", "Español" }));
        cbox1Materia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                obtenerMaterias(evt);
            }
        });
        cbox1Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaSeleccionada(evt);
            }
        });

        cbox2Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox2Grado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción", "3", "4", "5", "6" }));
        cbox2Grado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                obtenerGrados(evt);
            }
        });
        cbox2Grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradoSeleccionado(evt);
            }
        });

        cbox3Evaluacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox3Evaluacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));
        cbox3Evaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerGrupos(evt);
            }
        });

        javax.swing.GroupLayout jp2EvaluacionLayout = new javax.swing.GroupLayout(jp2Evaluacion);
        jp2Evaluacion.setLayout(jp2EvaluacionLayout);
        jp2EvaluacionLayout.setHorizontalGroup(
            jp2EvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2EvaluacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp2EvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab1Materia)
                    .addComponent(lab2Grado)
                    .addComponent(lab3Evaluacion))
                .addGap(18, 18, 18)
                .addGroup(jp2EvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2EvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbox1Materia, 0, 174, Short.MAX_VALUE)
                        .addComponent(cbox2Grado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbox3Evaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp2EvaluacionLayout.setVerticalGroup(
            jp2EvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2EvaluacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp2EvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp2EvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox2Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp2EvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab3Evaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox3Evaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boton2AplicarEvaluacion.setBackground(new java.awt.Color(51, 204, 0));
        boton2AplicarEvaluacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2AplicarEvaluacion.setText("Aplicar evaluación");
        boton2AplicarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarEvaluacion(evt);
            }
        });

        boton4Salir.setBackground(new java.awt.Color(255, 255, 255));
        boton4Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton4Salir.setText("Salir");
        boton4Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        jp4Reactivos.setBackground(new java.awt.Color(253, 251, 251));
        jp4Reactivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Vista previa de la valuación"));

        txta1Reactivo.setEditable(false);
        txta1Reactivo.setColumns(20);
        txta1Reactivo.setRows(5);
        jScrollPane1.setViewportView(txta1Reactivo);

        lab6A.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab6A.setText("A)");

        lab7B.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab7B.setText("B)");

        lab8C.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab8C.setText("C)");

        boton5Anterior.setText("<<Anterior");
        boton5Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReactivoAnterior(evt);
            }
        });

        boton6Siguiente.setText("Siguiente>>");
        boton6Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReactivoSiguiente(evt);
            }
        });

        lab5Reactivos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab5Reactivos.setText("Reactivo : 1 de total");

        lab9Respuesta1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab9Respuesta1.setText("Respuesta 1");

        lab11Respuesta3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab11Respuesta3.setText("Respuesta 3");

        lab10Respuesta2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab10Respuesta2.setText("Respuesta 2");

        javax.swing.GroupLayout jp4ReactivosLayout = new javax.swing.GroupLayout(jp4Reactivos);
        jp4Reactivos.setLayout(jp4ReactivosLayout);
        jp4ReactivosLayout.setHorizontalGroup(
            jp4ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4ReactivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp4ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4ReactivosLayout.createSequentialGroup()
                        .addGroup(jp4ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lab6A)
                            .addComponent(lab7B)
                            .addComponent(lab8C))
                        .addGap(18, 18, 18)
                        .addGroup(jp4ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab9Respuesta1)
                            .addComponent(lab11Respuesta3)
                            .addComponent(lab10Respuesta2)))
                    .addGroup(jp4ReactivosLayout.createSequentialGroup()
                        .addComponent(boton5Anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton6Siguiente))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4ReactivosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab5Reactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jp4ReactivosLayout.setVerticalGroup(
            jp4ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4ReactivosLayout.createSequentialGroup()
                .addComponent(lab5Reactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp4ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab6A, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab9Respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp4ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab7B, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab10Respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp4ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab8C, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab11Respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jp4ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton5Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton6Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jp3Grupo.setBackground(new java.awt.Color(253, 251, 251));
        jp3Grupo.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo a evaluar"));

        lab4Grupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab4Grupo.setText("Grupo:");

        cbox4Grupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox4Grupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción", "A", "B", "C" }));

        javax.swing.GroupLayout jp3GrupoLayout = new javax.swing.GroupLayout(jp3Grupo);
        jp3Grupo.setLayout(jp3GrupoLayout);
        jp3GrupoLayout.setHorizontalGroup(
            jp3GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3GrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab4Grupo)
                .addGap(52, 52, 52)
                .addComponent(cbox4Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jp3GrupoLayout.setVerticalGroup(
            jp3GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3GrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp3GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab4Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox4Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boton1VistaPrevia.setBackground(new java.awt.Color(255, 255, 0));
        boton1VistaPrevia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton1VistaPrevia.setText("Vista previa");
        boton1VistaPrevia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaPrevia(evt);
            }
        });

        boton3Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        boton3Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton3Cancelar.setText("Cancelar");
        boton3Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        javax.swing.GroupLayout jp1AplicarEvaluacionLayout = new javax.swing.GroupLayout(jp1AplicarEvaluacion);
        jp1AplicarEvaluacion.setLayout(jp1AplicarEvaluacionLayout);
        jp1AplicarEvaluacionLayout.setHorizontalGroup(
            jp1AplicarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1AplicarEvaluacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1AplicarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(boton3Cancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton2AplicarEvaluacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton4Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton1VistaPrevia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp1AplicarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp4Reactivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp2Evaluacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp3Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jp1AplicarEvaluacionLayout.setVerticalGroup(
            jp1AplicarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1AplicarEvaluacionLayout.createSequentialGroup()
                .addGroup(jp1AplicarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1AplicarEvaluacionLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(boton1VistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton2AplicarEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton3Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton4Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1AplicarEvaluacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jp2Evaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jp3Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp4Reactivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu1.setText("Mi cuenta");
        jMenu1.setToolTipText("");
        menu1.add(jMenu1);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1AplicarEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1AplicarEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 595, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //[13] cierra la interfaz
    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {
            limpiar();
            boton2AplicarEvaluacion.setEnabled(false);
            boton1VistaPrevia.setEnabled(true);
            boton2AplicarEvaluacion.setEnabled(false);
            cbox1Materia.setEnabled(true);
            cbox2Grado.setEnabled(true);
            cbox3Evaluacion.setEnabled(true);
            cbox3Evaluacion.removeAllItems();
            cbox3Evaluacion.addItem("Seleccione una opción");
            this.setVisible(false);

        }


    }//GEN-LAST:event_salir

    //[2] verifica si se ha seleccionado la materia
    private void materiaSeleccionada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaSeleccionada
        if (cbox1Materia.getSelectedIndex() != 0) {
            materiaSeleccionada = true;
        }
        if (materiaSeleccionada && gradoSeleccionado) {
            try {
                obtenerEvaluaciones();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazAplicarEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_materiaSeleccionada

    //[3] verifica si se ha seleccionado el grado
    private void gradoSeleccionado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradoSeleccionado
        if (cbox2Grado.getSelectedIndex() != 0) {
            gradoSeleccionado = true;
        }
        if (materiaSeleccionada && gradoSeleccionado) {
            try {
                obtenerEvaluaciones();
                //seleccionarEvaluacion();

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazAplicarEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_gradoSeleccionado

    //[5] valida los datos de seleccionados
    private void vistaPrevia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaPrevia
        if (materiaSeleccionada && gradoSeleccionado && cbox4Grupo.getSelectedIndex() != 0) {
            try {

                seleccionarEvaluacion();
                lab5Reactivos.setText("Reactivo : 1 de " + contenedordeReactivos.length);
                cbox1Materia.setEnabled(false);
                cbox2Grado.setEnabled(false);
                cbox3Evaluacion.setEnabled(false);
                boton2AplicarEvaluacion.setEnabled(true);

                posicionReactivo = 1;

                mostrarReactivo();
                boton1VistaPrevia.setEnabled(false);
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(rootPane, "NO HAY EVALUACIONES", "ERROR", JOptionPane.ERROR_MESSAGE);
                boton1VistaPrevia.setEnabled(true);
                boton2AplicarEvaluacion.setEnabled(false);

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "SELECCIONA:\nMateria\nGrado\nGrupo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_vistaPrevia

    //[7] muestra el reactivo indicado
    public void mostrarReactivo() {
        txta1Reactivo.setText(contenedordeReactivos[posicionReactivo - 1][1]);
        lab9Respuesta1.setText(contenedordeReactivos[posicionReactivo - 1][2]);
        lab10Respuesta2.setText(contenedordeReactivos[posicionReactivo - 1][3]);
        lab11Respuesta3.setText(contenedordeReactivos[posicionReactivo - 1][4]);

    }

    //[11] limpia todos los campos
    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        cbox1Materia.setEnabled(true);
        cbox2Grado.setEnabled(true);
        cbox3Evaluacion.setEnabled(true);
        lab5Reactivos.setText("Reactivo : 1 de 0");
        boton2AplicarEvaluacion.setEnabled(false);
        boton1VistaPrevia.setEnabled(true);

        limpiar();
    }//GEN-LAST:event_cancelar

    //[8] muestra el reactivo siguiente
    private void verReactivoSiguiente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verReactivoSiguiente
        try {
            if (posicionReactivo < contenedordeReactivos.length) {
                posicionReactivo++;
                lab5Reactivos.setText("Reactivo : " + (posicionReactivo) + " de " + contenedordeReactivos.length);
                mostrarReactivo();
            }
        } catch (NullPointerException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_verReactivoSiguiente

    //[9] muestra el reactivo anterior
    private void verReactivoAnterior(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verReactivoAnterior
        try {
            if (posicionReactivo > (1)) {
                posicionReactivo--;
                lab5Reactivos.setText("Reactivo : " + (posicionReactivo) + " de " + contenedordeReactivos.length);
                mostrarReactivo();
            }
        } catch (NullPointerException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_verReactivoAnterior

    //[10] asigna la evalaucion seleccionada para el grupo indicado
    private void aplicarEvaluacion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarEvaluacion
        if (materiaSeleccionada && gradoSeleccionado && cbox4Grupo.getSelectedIndex() != 0) {
            int respuesta = JOptionPane.showConfirmDialog(rootPane, "SEGURO QUIERE APLICAR LA EVALUACION?");
            if (respuesta == 0) {
                ControlEvaluacion evaluacion = new ControlEvaluacion();
                try {
                    System.out.println("idEvaluacion: " + idEvaluacion);
                    boolean existe = evaluacion.aplicarEvaluacion(idEvaluacion, (cbox2Grado.getSelectedIndex() + 2), cbox4Grupo.getSelectedItem().toString(), cbox1Materia.getSelectedIndex());
                    if (!existe) {
                        JOptionPane.showMessageDialog(rootPane, "EVALUACION APLICADA EXITOSAMENTE", "ALERTA", JOptionPane.WARNING_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "LA EVALUACION YA FUE APLICADA", "ERROR", JOptionPane.ERROR_MESSAGE);

                    }

                    limpiar();
                    boton1VistaPrevia.setEnabled(true);
                    boton2AplicarEvaluacion.setEnabled(false);
                    cbox1Materia.setEnabled(true);
                    cbox2Grado.setEnabled(true);
                    cbox3Evaluacion.setEnabled(true);
                    cbox3Evaluacion.removeAllItems();
                    cbox3Evaluacion.addItem("Seleccione una opción");

                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(InterfazAplicarEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "SELECCIONA:\nMateria\nGrado\nGrupo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_aplicarEvaluacion

    //[1] establece el nombre y el id de usuario a la interfaz
    private void personalizarInterfaz(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_personalizarInterfaz
        jMenu1.setText("Mi cuenta: " + nombre + " : " + idUsuario);
    }//GEN-LAST:event_personalizarInterfaz

    private void obtenerGrados(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_obtenerGrados
        // TODO add your handling code here:
        ControlGrupo Cgrupo = new ControlGrupo();
        try {
            ResultSet obtenerGrados = Cgrupo.obtenerGrupos();

            String grado = "";

            while (obtenerGrados.next()) {
                grado = obtenerGrados.getObject(1).toString();
                int totalGrado = cbox2Grado.getItemCount();
                int maximo = 0;

                for (int i = 0; i < totalGrado; i++) {
                    if (grado.compareTo(cbox2Grado.getItemAt(i).toString()) == 0) {
                        maximo++;

                    }
                }
                if (maximo == 0) {
                    this.cbox2Grado.addItem(grado);
                }

            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error al intentar obtener datos a la bd");
        }

    }//GEN-LAST:event_obtenerGrados

    private void obtenerMaterias(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_obtenerMaterias
        // TODO add your handling code here:
        limpiar();
        ControlMateria cMateria = new ControlMateria();
        try {
            ResultSet obtenerMaterias = cMateria.obtenerMaterias();

            while (obtenerMaterias.next()) {
                cbox1Materia.addItem(obtenerMaterias.getObject(1));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_obtenerMaterias

    private void obtenerGrupos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerGrupos
        // TODO add your handling code here:
        cbox4Grupo.removeAllItems();
        cbox4Grupo.addItem("Seleccione una opción");
        ControlGrupo Cgrupo = new ControlGrupo();
        try {
            ResultSet obtenerGrupos = Cgrupo.obtenerGrupos(Integer.parseInt(cbox2Grado.getSelectedItem().toString()));
            System.out.println("seleccione: " + cbox2Grado.getSelectedItem().toString());
            String grupo = "";

            while (obtenerGrupos.next()) {
                grupo = obtenerGrupos.getObject(1).toString();
                this.cbox4Grupo.addItem(grupo);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error al intentar obtener datos a la bd");
        } catch (NumberFormatException | NullPointerException ex) {
        }


    }//GEN-LAST:event_obtenerGrupos

    //[6] se obtienen los reactivos de la evaluacion seleccionada
    public void seleccionarEvaluacion() {

        if (materiaSeleccionada && gradoSeleccionado) {
            ControlEvaluacion evaluacion = new ControlEvaluacion();
            try {

                //obtiene informacion del contenido de la evaluacion
                ResultSet contenido = evaluacion.consultarDatosyContenido(cbox3Evaluacion.getSelectedItem().toString());

                //asignando los id de los reactivos dentro de un vector
                while (contenido.next()) {
                    contenedordeReactivos = new String[Integer.parseInt(contenido.getObject(5).toString())][5];
                    idEvaluacion = Integer.parseInt(contenido.getObject(1).toString());
                    for (int i = 0; i < Integer.parseInt(contenido.getObject(5).toString()); i++) {
                        contenedordeReactivos[i][0] = contenido.getObject((i + 9)).toString();

                    }
                }

                //llena en el vector de contenedor con los reactivos con sus respectivas respuestas
                ControlReactivo reactivo = new ControlReactivo();
                ResultSet consulta = null;

                for (int renglon = 0; renglon < contenedordeReactivos.length; renglon++) {
                    for (int columna = 0; columna < contenedordeReactivos[renglon].length; columna++) {

                        if (columna == 0) {
                            //obtiene los reactivos de la evaluacion
                            consulta = reactivo.consultar(Integer.parseInt(contenedordeReactivos[renglon][columna]));
                            consulta.next();
                        }
                        if (columna < 4) {
                            contenedordeReactivos[renglon][(columna + 1)] = consulta.getObject(columna + 1).toString();

                        }

                    }
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazAplicarEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NullPointerException e) {
                System.out.println(e);
            }
        }
    }

    //[12] limpia cada campo en la interfaz
    public void limpiar() {
        cbox1Materia.removeAllItems();
        cbox1Materia.addItem("Seleccione una opción");

        cbox2Grado.removeAllItems();
        cbox2Grado.addItem("Seleccione una opción");

        cbox3Evaluacion.removeAllItems();
        cbox3Evaluacion.addItem("Seleccione una opción");
        txta1Reactivo.setText("");
        lab9Respuesta1.setText("Respuesta1");
        lab10Respuesta2.setText("Respuesta2");
        lab11Respuesta3.setText("Respuesta3");
        lab5Reactivos.setText("Reactivo : 0 de 0");

    }

    //[4] obtiene el nombre de las evaluaciones y se muestran
    public void obtenerEvaluaciones() throws ClassNotFoundException, SQLException {
        ControlEvaluacion evaluacion = new ControlEvaluacion();
        ResultSet resultadoConsulta = evaluacion.consultarNombreEvaluacion(cbox1Materia.getSelectedIndex(), (cbox2Grado.getSelectedIndex() + 2));
        cbox3Evaluacion.removeAllItems();
        cbox3Evaluacion.addItem("Seleccione una opción");
        while (resultadoConsulta.next()) {
            cbox3Evaluacion.addItem(resultadoConsulta.getObject(1));

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAplicarEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAplicarEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAplicarEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAplicarEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAplicarEvaluacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1VistaPrevia;
    private javax.swing.JButton boton2AplicarEvaluacion;
    private javax.swing.JButton boton3Cancelar;
    private javax.swing.JButton boton4Salir;
    private javax.swing.JButton boton5Anterior;
    private javax.swing.JButton boton6Siguiente;
    private javax.swing.JComboBox cbox1Materia;
    private javax.swing.JComboBox cbox2Grado;
    private javax.swing.JComboBox cbox3Evaluacion;
    private javax.swing.JComboBox cbox4Grupo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp1AplicarEvaluacion;
    private javax.swing.JPanel jp2Evaluacion;
    private javax.swing.JPanel jp3Grupo;
    private javax.swing.JPanel jp4Reactivos;
    private javax.swing.JLabel lab10Respuesta2;
    private javax.swing.JLabel lab11Respuesta3;
    private javax.swing.JLabel lab1Materia;
    private javax.swing.JLabel lab2Grado;
    private javax.swing.JLabel lab3Evaluacion;
    private javax.swing.JLabel lab4Grupo;
    private javax.swing.JLabel lab5Reactivos;
    private javax.swing.JLabel lab6A;
    private javax.swing.JLabel lab7B;
    private javax.swing.JLabel lab8C;
    private javax.swing.JLabel lab9Respuesta1;
    private javax.swing.JMenuBar menu1;
    private javax.swing.JTextArea txta1Reactivo;
    // End of variables declaration//GEN-END:variables
}
