/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteMantenimientodeReactivos;

import PaqueteMantenimientoUsuarios.ControlGrupo;
import PaqueteMantenimientodeMaterias.ControlMateria;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazModificarReactivos extends javax.swing.JFrame {

    int contarTotalComentario;
    int contarTotalReactivos;
    boolean materiaSeleccionada = false;
    boolean gradoSeleccionado = false;
    public int idUsuario;
    public String nombre;

    /**
     * Creates new form InterfazModificarReactivos
     */
    public InterfazModificarReactivos() {
        initComponents();
        //establece la posicion central de la interfaz
        this.setLocationRelativeTo(null);

        //coloca el icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        //desactiva la opcion maximizar
        this.setResizable(false);
        //desactiva la opcion cerrar
        setDefaultCloseOperation(0);

        //desactiva las opciones de ingreso de texto
        txta1Reactivo.setEnabled(false);
        txt1RespuestaCorrecta.setEnabled(false);
        txt3RespuestaIncorrecta1.setEnabled(false);
        txt2RespuestaIncorrecta2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jp1ModificarReactivos = new javax.swing.JPanel();
        jp2DatosReactivo = new javax.swing.JPanel();
        cbox1Materia = new javax.swing.JComboBox();
        lab1TotaldeReactivos = new javax.swing.JLabel();
        cbox3Tema = new javax.swing.JComboBox();
        cbox2Grado = new javax.swing.JComboBox();
        lab8Grado = new javax.swing.JLabel();
        lab9Tema = new javax.swing.JLabel();
        lab7Materia = new javax.swing.JLabel();
        boton1Consultar = new javax.swing.JButton();
        boton2Guardar = new javax.swing.JButton();
        boton3Salir = new javax.swing.JButton();
        jp5Reactivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1Reactivos = new javax.swing.JTable();
        jp4Reactivo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta1Reactivo = new javax.swing.JTextArea();
        lab3RespuestaCorrecta = new javax.swing.JLabel();
        lab4RespuestaIncorrecta1 = new javax.swing.JLabel();
        lab5RespuestaIncorrecta2 = new javax.swing.JLabel();
        txt1RespuestaCorrecta = new javax.swing.JTextField();
        txt3RespuestaIncorrecta1 = new javax.swing.JTextField();
        txt2RespuestaIncorrecta2 = new javax.swing.JTextField();
        lab6TotalCaracteres = new javax.swing.JLabel();
        jp3Comentarios = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2Comentarios = new javax.swing.JTable();
        lab2TotalComentarios = new javax.swing.JLabel();
        boton4Cancelar = new javax.swing.JButton();
        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MantenimientoDeReactivos/ModificarReactivos");
        setMinimumSize(new java.awt.Dimension(918, 214));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                personalizarInterfaz(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jp1ModificarReactivos.setBackground(new java.awt.Color(245, 245, 239));
        jp1ModificarReactivos.setMaximumSize(new java.awt.Dimension(910, 714));

        jp2DatosReactivo.setBackground(new java.awt.Color(253, 251, 251));
        jp2DatosReactivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del reactivo"));

        cbox1Materia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox1Materia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));
        cbox1Materia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscarMaterias(evt);
            }
        });
        cbox1Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaSeleccionada(evt);
            }
        });

        lab1TotaldeReactivos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab1TotaldeReactivos.setText("Total de reactivos: #0");

        cbox3Tema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox3Tema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));

        cbox2Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox2Grado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));
        cbox2Grado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                obtenerGrados(evt);
            }
        });
        cbox2Grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradoSeleccionado(evt);
            }
        });

        lab8Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab8Grado.setText("Grado:");

        lab9Tema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab9Tema.setText("Tema:");

        lab7Materia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab7Materia.setText("Materia:");

        javax.swing.GroupLayout jp2DatosReactivoLayout = new javax.swing.GroupLayout(jp2DatosReactivo);
        jp2DatosReactivo.setLayout(jp2DatosReactivoLayout);
        jp2DatosReactivoLayout.setHorizontalGroup(
            jp2DatosReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2DatosReactivoLayout.createSequentialGroup()
                .addGroup(jp2DatosReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab7Materia)
                    .addComponent(lab8Grado)
                    .addComponent(lab9Tema))
                .addGap(18, 18, 18)
                .addGroup(jp2DatosReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2DatosReactivoLayout.createSequentialGroup()
                        .addComponent(cbox3Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp2DatosReactivoLayout.createSequentialGroup()
                        .addGroup(jp2DatosReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbox1Materia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbox2Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lab1TotaldeReactivos)
                        .addGap(35, 35, 35))))
        );
        jp2DatosReactivoLayout.setVerticalGroup(
            jp2DatosReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2DatosReactivoLayout.createSequentialGroup()
                .addGroup(jp2DatosReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab7Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab1TotaldeReactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp2DatosReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab8Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox2Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp2DatosReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab9Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox3Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boton1Consultar.setBackground(new java.awt.Color(255, 255, 51));
        boton1Consultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton1Consultar.setText("Consultar");
        boton1Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar(evt);
            }
        });

        boton2Guardar.setBackground(new java.awt.Color(51, 204, 0));
        boton2Guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2Guardar.setText("Guardar");
        boton2Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });

        boton3Salir.setBackground(new java.awt.Color(255, 255, 255));
        boton3Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton3Salir.setText("Salir");
        boton3Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        jp5Reactivos.setBackground(new java.awt.Color(253, 251, 251));
        jp5Reactivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el reactivo a modificar"));

        table1Reactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de lista", "Descripción del reactivo", "Respuesta correcta", "Respuesta Incorrecta 1", "Respuesta Incorrecta 2"
            }
        ));
        table1Reactivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarComentarios(evt);
            }
        });
        jScrollPane1.setViewportView(table1Reactivos);

        javax.swing.GroupLayout jp5ReactivosLayout = new javax.swing.GroupLayout(jp5Reactivos);
        jp5Reactivos.setLayout(jp5ReactivosLayout);
        jp5ReactivosLayout.setHorizontalGroup(
            jp5ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5ReactivosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jp5ReactivosLayout.setVerticalGroup(
            jp5ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jp4Reactivo.setBackground(new java.awt.Color(253, 251, 251));
        jp4Reactivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción del reactivo"));

        txta1Reactivo.setColumns(20);
        txta1Reactivo.setRows(5);
        txta1Reactivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contarCaracteres(evt);
            }
        });
        jScrollPane2.setViewportView(txta1Reactivo);

        lab3RespuestaCorrecta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab3RespuestaCorrecta.setText("Respuesta Correcta:");

        lab4RespuestaIncorrecta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab4RespuestaIncorrecta1.setText("Respuesta Incorrecta 1:");

        lab5RespuestaIncorrecta2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab5RespuestaIncorrecta2.setText("Respuesta Incorrecta 2:");

        txt1RespuestaCorrecta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txt3RespuestaIncorrecta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txt2RespuestaIncorrecta2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lab6TotalCaracteres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab6TotalCaracteres.setText("Caracteres: 0");

        javax.swing.GroupLayout jp4ReactivoLayout = new javax.swing.GroupLayout(jp4Reactivo);
        jp4Reactivo.setLayout(jp4ReactivoLayout);
        jp4ReactivoLayout.setHorizontalGroup(
            jp4ReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4ReactivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp4ReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab6TotalCaracteres, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp4ReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab4RespuestaIncorrecta1)
                    .addComponent(lab3RespuestaCorrecta)
                    .addComponent(lab5RespuestaIncorrecta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp4ReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt1RespuestaCorrecta)
                    .addComponent(txt3RespuestaIncorrecta1)
                    .addComponent(txt2RespuestaIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jp4ReactivoLayout.setVerticalGroup(
            jp4ReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4ReactivoLayout.createSequentialGroup()
                .addGroup(jp4ReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4ReactivoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab6TotalCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp4ReactivoLayout.createSequentialGroup()
                        .addGroup(jp4ReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1RespuestaCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab3RespuestaCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp4ReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab4RespuestaIncorrecta1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt3RespuestaIncorrecta1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp4ReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2RespuestaIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab5RespuestaIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jp3Comentarios.setBackground(new java.awt.Color(253, 251, 251));
        jp3Comentarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Comentarios"));

        table2Comentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de lista", "Numero de empleado", "Comentario", "Fecha"
            }
        ));
        jScrollPane3.setViewportView(table2Comentarios);
        if (table2Comentarios.getColumnModel().getColumnCount() > 0) {
            table2Comentarios.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        lab2TotalComentarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab2TotalComentarios.setText("Total de comentarios: #0");

        javax.swing.GroupLayout jp3ComentariosLayout = new javax.swing.GroupLayout(jp3Comentarios);
        jp3Comentarios.setLayout(jp3ComentariosLayout);
        jp3ComentariosLayout.setHorizontalGroup(
            jp3ComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3ComentariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp3ComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3ComentariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lab2TotalComentarios))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jp3ComentariosLayout.setVerticalGroup(
            jp3ComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3ComentariosLayout.createSequentialGroup()
                .addComponent(lab2TotalComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        boton4Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        boton4Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton4Cancelar.setText("Cancelar");
        boton4Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        javax.swing.GroupLayout jp1ModificarReactivosLayout = new javax.swing.GroupLayout(jp1ModificarReactivos);
        jp1ModificarReactivos.setLayout(jp1ModificarReactivosLayout);
        jp1ModificarReactivosLayout.setHorizontalGroup(
            jp1ModificarReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1ModificarReactivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1ModificarReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1ModificarReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(boton2Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton1Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(boton3Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(boton4Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp1ModificarReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp4Reactivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp2DatosReactivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1ModificarReactivosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jp5Reactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jp3Comentarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jp1ModificarReactivosLayout.setVerticalGroup(
            jp1ModificarReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1ModificarReactivosLayout.createSequentialGroup()
                .addGroup(jp1ModificarReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1ModificarReactivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jp2DatosReactivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1ModificarReactivosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(boton1Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton4Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton3Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp5Reactivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp3Comentarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp1ModificarReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1ModificarReactivosLayout.createSequentialGroup()
                        .addComponent(boton2Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp1ModificarReactivosLayout.createSequentialGroup()
                        .addComponent(jp4Reactivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 61, Short.MAX_VALUE))))
        );

        jScrollPane4.setViewportView(jp1ModificarReactivos);

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu1.setToolTipText("");
        menu1.add(jMenu1);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //[15] cierra la interfaz
    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {
            limpiarReactivos();
            limpiarCampos();
            //bloquea el ingreso de texto
            txta1Reactivo.setEnabled(false);
            txt1RespuestaCorrecta.setEnabled(false);
            txt3RespuestaIncorrecta1.setEnabled(false);
            txt2RespuestaIncorrecta2.setEnabled(false);

            lab6TotalCaracteres.setText("Caracteres: 0");
            lab2TotalComentarios.setText("Total de comentarios: #0");

            DefaultTableModel modelo = (DefaultTableModel) table2Comentarios.getModel();
            int total = table2Comentarios.getRowCount();
            for (int i = 0; i < total; i++) {
                modelo.removeRow(0);
            }
            this.setVisible(false);

        }
    }//GEN-LAST:event_salir

    //[2] verifica si se ha seleccionado la materia
    private void materiaSeleccionada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaSeleccionada
        limpiarReactivos();
        if (cbox1Materia.getSelectedIndex() != 0) {
            materiaSeleccionada = true;
            obtenerTemas();

        } else {
            materiaSeleccionada = false;
            obtenerTemas();

        }
        lab1TotaldeReactivos.setText("Total de reactivos: #0");
    }//GEN-LAST:event_materiaSeleccionada

    //[3] verifica si se ha seleccionado el grado
    private void gradoSeleccionado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradoSeleccionado
        // TODO add your handling code here:
        limpiarReactivos();
        if (cbox2Grado.getSelectedIndex() != 0) {
            gradoSeleccionado = true;
            obtenerTemas();

        } else {
            gradoSeleccionado = false;
            obtenerTemas();

        }
        lab1TotaldeReactivos.setText("Total de reactivos: #0");
    }//GEN-LAST:event_gradoSeleccionado

    //[5] busca los reactivos en relacion a la materia, tema y grado
    private void consultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar
        limpiarReactivos();
        lab1TotaldeReactivos.setText("Total de reactivos: #0");
        if (materiaSeleccionada && gradoSeleccionado && cbox3Tema.getSelectedIndex() > 0) {

            table1Reactivos.removeAll();
            ControlReactivo reactivo = new ControlReactivo();

            try {
                System.out.println(cbox1Materia.getSelectedIndex() + " " + cbox3Tema.getItemAt(cbox3Tema.getSelectedIndex()).toString() + " " + (cbox2Grado.getSelectedIndex() + 2));
                ResultSet consultar = reactivo.consultarReactivos(cbox1Materia.getSelectedIndex(), cbox3Tema.getItemAt(cbox3Tema.getSelectedIndex()).toString(), (cbox2Grado.getSelectedIndex() + 2));

                llenarReactivos(consultar);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazModificarReactivos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "SELECCIONA LA MATERIA, EL GRADO Y TEMA", "ERROR", JOptionPane.ERROR_MESSAGE);
            table1Reactivos.removeAll();
        }

    }//GEN-LAST:event_consultar

    //[11] guarda lo modificado en la base de datos
    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        // TODO add your handling code here:
        if (materiaSeleccionada && gradoSeleccionado && (txta1Reactivo.getText().length() >= 5)
                && (txt1RespuestaCorrecta.getText().length() > 0)
                && (txt3RespuestaIncorrecta1.getText().length() > 0)
                && (txt2RespuestaIncorrecta2.getText().length() > 0)
                && hayEspaciosEnBlanco(txta1Reactivo.getText()) == false
                && hayEspaciosEnBlanco(txt1RespuestaCorrecta.getText()) == false
                && hayEspaciosEnBlanco(txt3RespuestaIncorrecta1.getText()) == false
                && hayEspaciosEnBlanco(txt2RespuestaIncorrecta2.getText()) == false) {
            if ((txta1Reactivo.getText().length() <= 150)) {

                ControlReactivo reactivoC = new ControlReactivo();

                try {
                    int resultadoConfirmacion = JOptionPane.showConfirmDialog(rootPane, "TODO ESTA CORRECTO?", "ALERTA", JOptionPane.OK_CANCEL_OPTION);
                    if (resultadoConfirmacion == 0) {

                        //valida que el usuario haya creado el reactivo
                        int resultadoIdUsuario = reactivoC.obtenerCreadordelReactivo(
                                table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 1).toString(),
                                table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 2).toString(),
                                table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 3).toString(),
                                table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 4).toString());

                        if (resultadoIdUsuario == idUsuario) {
                            boolean existe = reactivoC.existeReactivo(txta1Reactivo.getText(), txt1RespuestaCorrecta.getText(), txt3RespuestaIncorrecta1.getText(), txt2RespuestaIncorrecta2.getText());
                            if (existe == false) {

                                reactivoC.modificar(idUsuario,
                                        table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 1).toString(),
                                        table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 2).toString(),
                                        table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 3).toString(),
                                        table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 4).toString(),
                                        txta1Reactivo.getText(),
                                        txt1RespuestaCorrecta.getText(),
                                        txt3RespuestaIncorrecta1.getText(),
                                        txt2RespuestaIncorrecta2.getText());

                                txta1Reactivo.setText("");
                                txt1RespuestaCorrecta.setText("");
                                txt3RespuestaIncorrecta1.setText("");
                                txt2RespuestaIncorrecta2.setText("");

                                ActionEvent evento = null;
                                consultar(evento);
                                JOptionPane.showMessageDialog(rootPane, "REACTIVO MODIFICADO CON EXITO", "FELICIDADES", JOptionPane.WARNING_MESSAGE);

                            } else {
                                JOptionPane.showMessageDialog(rootPane, "EL REACTIVO YA EXISTE", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }

                        } else {
                            JOptionPane.showMessageDialog(rootPane, "SOLO EL CREADOR DEL REACTIVO PUEDE MODIFICARLO", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }

                    }

                } catch (SQLException | ClassNotFoundException ex) {
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "EL REACTIVO TIENE MAS DE 150 CARACTERES", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            String mensaje = "";
            mensaje = datosPorIngresar();
            JOptionPane.showMessageDialog(rootPane, "NO DEJES CAMPOS VACIOS\n INGRESE LOS SIGUIENTES CAMPOS:\n" + mensaje + "", "ERROR", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_guardar

    //[7] busca los comentarios que estan relacionados al reactivo
    private void buscarComentarios(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarComentarios
        permitirModificarReactivo();

        ControlComentario comentario = new ControlComentario();

        try {
            limpiarComentarios();
            String reactivo = table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 1).toString();
            ResultSet[] resultados = comentario.consultar(reactivo);
            llenarComentarios(resultados);
        } catch (NullPointerException | ArrayIndexOutOfBoundsException e) {
            System.out.println(e);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_buscarComentarios

    //[10] cuenta los caracteres del comentario a ingresar
    private void contarCaracteres(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contarCaracteres
        int totaldeCaracteres = txta1Reactivo.getText().length();
        lab6TotalCaracteres.setText("Caracteres: " + totaldeCaracteres);
        if (totaldeCaracteres > 150) {
            lab6TotalCaracteres.setForeground(Color.red);

        } else {
            lab6TotalCaracteres.setForeground(Color.black);
        }
    }//GEN-LAST:event_contarCaracteres

    //[1] muestra el nombre y el id del usuario
    private void personalizarInterfaz(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_personalizarInterfaz
        // TODO add your handling code here:
        jMenu1.setText("Mi cuenta: " + nombre + " : " + idUsuario);
    }//GEN-LAST:event_personalizarInterfaz

    //[14] limpia los datos de la interfaz
    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        // TODO add your handling code here:
        limpiarReactivos();
        limpiarCampos();
        cbox3Tema.removeAllItems();
        cbox3Tema.addItem("Seleccione una opción");
        txta1Reactivo.setEnabled(false);
        txt1RespuestaCorrecta.setEnabled(false);
        txt3RespuestaIncorrecta1.setEnabled(false);
        txt2RespuestaIncorrecta2.setEnabled(false);
        lab6TotalCaracteres.setText("Caracteres: 0");
        lab2TotalComentarios.setText("Total de comentarios: #0");

        DefaultTableModel modelo = (DefaultTableModel) table2Comentarios.getModel();
        int total = table2Comentarios.getRowCount();
        for (int i = 0; i < total; i++) {
            modelo.removeRow(0);
        }


    }//GEN-LAST:event_cancelar

    private void buscarMaterias(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarMaterias
        // TODO add your handling code here:

        // TODO add your handling code here:
        limpiarCampos();
        ControlMateria cMateria = new ControlMateria();
        try {
            ResultSet obtenerMaterias = cMateria.obtenerMaterias();

            while (obtenerMaterias.next()) {
                cbox1Materia.addItem(obtenerMaterias.getObject(1));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_buscarMaterias

    private void obtenerGrados(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_obtenerGrados
        // TODO add your handling code here:
        ControlGrupo Cgrupo = new ControlGrupo();
        try {
            ResultSet obtenerGrados = Cgrupo.obtenerGrupos();

            String grado = "";

            while (obtenerGrados.next()) {
                grado = obtenerGrados.getObject(1).toString();
                int totalGrado = cbox2Grado.getItemCount();
                int maximo = 0;

                for (int i = 0; i < totalGrado; i++) {
                    if (grado.compareTo(cbox2Grado.getItemAt(i).toString()) == 0) {
                        maximo++;

                    }
                }
                if (maximo == 0) {
                    this.cbox2Grado.addItem(grado);
                }

            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error al intentar obtener datos a la bd");
        }


    }//GEN-LAST:event_obtenerGrados

    //[9] permite modificar el reactivo asi como sus respuestas
    public void permitirModificarReactivo() {
        txta1Reactivo.setEnabled(true);
        txt1RespuestaCorrecta.setEnabled(true);
        txt3RespuestaIncorrecta1.setEnabled(true);
        txt2RespuestaIncorrecta2.setEnabled(true);
        try {
            txta1Reactivo.setText(table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 1).toString());
            txt1RespuestaCorrecta.setText(table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 2).toString());
            txt3RespuestaIncorrecta1.setText(table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 3).toString());
            txt2RespuestaIncorrecta2.setText(table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 4).toString());

            lab6TotalCaracteres.setText("Caracteres: " + txta1Reactivo.getText().length());
        } catch (NullPointerException e) {
            System.out.println(e);
        }
    }

    //[17] remeuve los comentarios 
    public void limpiarComentarios() {
        // TODO add your handling code here:
        try {

            DefaultTableModel modelo = (DefaultTableModel) table2Comentarios.getModel();
            int total = table2Comentarios.getRowCount();
            for (int i = 0; i < total; i++) {
                modelo.removeRow(0);
            }

        } catch (NumberFormatException e) {
            System.out.println(e.toString());
        }

    }

    //[8] muestra en la tabla los comentarios
    public void llenarComentarios(ResultSet conjuntoResultados[]) throws SQLException {
        int posicion = 0;

        DefaultTableModel modelo = (DefaultTableModel) table2Comentarios.getModel();

        while (conjuntoResultados[0].next()) {
            modelo.addRow(new Object[]{
                "",
                "",
                conjuntoResultados[0].getObject(1).toString(),
                conjuntoResultados[0].getObject(2).toString()
            });

            posicion++;

        }//find el while

        posicion = 0;

        while (conjuntoResultados[1].next()) {
            table2Comentarios.setValueAt((posicion + 1), posicion, 0);
            table2Comentarios.setValueAt(conjuntoResultados[1].getObject(1).toString(), posicion, 1);
            posicion++;
        }
        contarTotalComentario = posicion;
        lab2TotalComentarios.setText("Total de comentarios: #" + contarTotalComentario);

    }

    //[6] inserta los reactivos en la tabla
    public void llenarReactivos(ResultSet conjuntoResultados) throws ClassNotFoundException, SQLException {
        table1Reactivos.removeAll();
        int posicion = 0;

        DefaultTableModel modelo = (DefaultTableModel) table1Reactivos.getModel();

        while (conjuntoResultados.next()) {
            modelo.addRow(new Object[]{
                (posicion + 1),
                conjuntoResultados.getObject(1).toString(),
                conjuntoResultados.getObject(2).toString(),
                conjuntoResultados.getObject(3).toString(),
                conjuntoResultados.getObject(4).toString()
            });
            posicion++;
        }//find el while
        contarTotalReactivos = posicion;
        lab1TotaldeReactivos.setText("Total de reactivos: #" + contarTotalReactivos);

    }

    //[16] remueve los reactivos
    public void limpiarReactivos() {
        try {

            DefaultTableModel modelo = (DefaultTableModel) table1Reactivos.getModel();
            int total = table1Reactivos.getRowCount();
            for (int i = 0; i < total; i++) {
                modelo.removeRow(0);
            }

        } catch (NumberFormatException e) {
            System.out.println(e.toString());
        }

    }

    //[4] obtiene y muestra los temas relacionados a la materia y grado
    public void obtenerTemas() {
        cbox3Tema.removeAllItems();
        cbox3Tema.addItem("Seleccione una opción");
        ControlTema temaC = new ControlTema();
        if (materiaSeleccionada && gradoSeleccionado) {
            try {

                ResultSet resultado = temaC.consultarTemas((cbox1Materia.getSelectedIndex()), (cbox2Grado.getSelectedIndex() + 2));

                while (resultado.next()) {

                    cbox3Tema.addItem(resultado.getObject(1));

                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazModificarReactivos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            cbox3Tema.removeAllItems();
            cbox3Tema.addItem("Seleccione una opción");
        }

    }

    //[13] indica los datos que falta ingresar
    public String datosPorIngresar() {
        String mensaje = "";
        if (materiaSeleccionada && !gradoSeleccionado) {

            mensaje = mensaje + "-Grado\n";
            mensaje = mensaje + "-Tema\n";
            cbox3Tema.removeAllItems();

        } else if (!materiaSeleccionada && gradoSeleccionado) {

            mensaje = mensaje + "-Materia\n";
            mensaje = mensaje + "-Tema\n";
            cbox3Tema.removeAllItems();

        } else if (!materiaSeleccionada && !gradoSeleccionado) {

            mensaje = mensaje + "-Materia\n";
            mensaje = mensaje + "-Grado\n";
            mensaje = mensaje + "-Tema\n";
            cbox3Tema.removeAllItems();
        }
        if (txta1Reactivo.getText().length() <= 0 || hayEspaciosEnBlanco(txta1Reactivo.getText()) || txta1Reactivo.getText().length() <= 5) {
            mensaje = mensaje + "-Descripción del reactivo muy corta\n";
        }
        if (txt1RespuestaCorrecta.getText().length() <= 0 || hayEspaciosEnBlanco(txt1RespuestaCorrecta.getText())) {
            mensaje = mensaje + "-RespuestaCorrecta\n";
        }
        if (txt3RespuestaIncorrecta1.getText().length() <= 0 || hayEspaciosEnBlanco(txt3RespuestaIncorrecta1.getText())) {
            mensaje = mensaje + "-RespuestaIncorrecta1\n";
        }
        if (txt2RespuestaIncorrecta2.getText().length() <= 0 || hayEspaciosEnBlanco(txt2RespuestaIncorrecta2.getText())) {
            mensaje = mensaje + "-RespuestaIncorrecta2\n";
        }
        return mensaje;
    }

    //[18] limpia todos los campos de la interfaz
    public void limpiarCampos() {

        cbox1Materia.removeAllItems();
        cbox1Materia.addItem("Seleccione una opción");

        cbox2Grado.removeAllItems();
        cbox2Grado.addItem("Seleccione una opción");

        cbox3Tema.removeAllItems();
        cbox3Tema.addItem("Seleccione una opción");
        txta1Reactivo.setText("");
        txt1RespuestaCorrecta.setText("");
        txt3RespuestaIncorrecta1.setText("");
        txt2RespuestaIncorrecta2.setText("");

    }

    //[12] verifica si existen espacios en blanco en el texto
    public boolean hayEspaciosEnBlanco(String texto) {
        boolean resultado = false;

        for (int i = 0; i < texto.length(); i++) {

            if ((int) texto.charAt(i) == 32) {
                resultado = true;
            } else {
                return false;
            }

        }

        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarReactivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarReactivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarReactivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarReactivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazModificarReactivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1Consultar;
    private javax.swing.JButton boton2Guardar;
    private javax.swing.JButton boton3Salir;
    private javax.swing.JButton boton4Cancelar;
    private javax.swing.JComboBox cbox1Materia;
    private javax.swing.JComboBox cbox2Grado;
    private javax.swing.JComboBox cbox3Tema;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jp1ModificarReactivos;
    private javax.swing.JPanel jp2DatosReactivo;
    private javax.swing.JPanel jp3Comentarios;
    private javax.swing.JPanel jp4Reactivo;
    private javax.swing.JPanel jp5Reactivos;
    private javax.swing.JLabel lab1TotaldeReactivos;
    private javax.swing.JLabel lab2TotalComentarios;
    private javax.swing.JLabel lab3RespuestaCorrecta;
    private javax.swing.JLabel lab4RespuestaIncorrecta1;
    private javax.swing.JLabel lab5RespuestaIncorrecta2;
    private javax.swing.JLabel lab6TotalCaracteres;
    private javax.swing.JLabel lab7Materia;
    private javax.swing.JLabel lab8Grado;
    private javax.swing.JLabel lab9Tema;
    private javax.swing.JMenuBar menu1;
    private javax.swing.JTable table1Reactivos;
    private javax.swing.JTable table2Comentarios;
    private javax.swing.JTextField txt1RespuestaCorrecta;
    private javax.swing.JTextField txt2RespuestaIncorrecta2;
    private javax.swing.JTextField txt3RespuestaIncorrecta1;
    private javax.swing.JTextArea txta1Reactivo;
    // End of variables declaration//GEN-END:variables
}
