/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteMantenimientodeReactivos;

import PaqueteLogin.InterfazLogin;
import PaqueteMantenimientoUsuarios.ControlGrupo;
import PaqueteMantenimientodeMaterias.ControlMateria;
import com.inet.jortho.FileUserDictionary;
import com.inet.jortho.SpellChecker;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazConsultaDeReactivos extends javax.swing.JFrame {

    int contarTotalReactivos;
    int contarTotalComentario;
    boolean materiaSeleccionada = false;
    boolean gradoSeleccionado = false;
    public int idUsuario;
    public String nombre;

    /**
     * Creates new form InterfazConsultaDeReactivos
     */
    public InterfazConsultaDeReactivos() {
        initComponents();

        //verifica la ortografia
        SpellChecker.setUserDictionaryProvider(new FileUserDictionary());
        SpellChecker.registerDictionaries(null, null);
        SpellChecker.register(txta1Comentario);

        //establece la posicion central de la interfaz
        this.setLocationRelativeTo(null);

        //coloca el icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        //desactiva la opcion maximizar
        this.setResizable(false);
        //desactiva la opcion cerrar
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jp1ConsultaReactivos = new javax.swing.JPanel();
        jp2InformacionReactivo = new javax.swing.JPanel();
        lab2Materia = new javax.swing.JLabel();
        lab3Grado = new javax.swing.JLabel();
        lab7Tema = new javax.swing.JLabel();
        cbox1Materia = new javax.swing.JComboBox();
        cbox2Grado = new javax.swing.JComboBox();
        cbox3Tema = new javax.swing.JComboBox();
        lab1TotaldeReactivos = new javax.swing.JLabel();
        jp3Reactivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1Reactivos = new javax.swing.JTable();
        jp5Comentario = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta1Comentario = new javax.swing.JTextArea();
        lab4Caracteres = new javax.swing.JLabel();
        lab5MaximoCaracteres = new javax.swing.JLabel();
        jp4Comentarios = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table2Comentarios = new javax.swing.JTable();
        lab6TotalComentarios = new javax.swing.JLabel();
        boton3Salir = new javax.swing.JButton();
        boton1Consultar = new javax.swing.JButton();
        boton2Comentar = new javax.swing.JButton();
        boton4Cancelar = new javax.swing.JButton();
        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MantenimientoDeReactivos/ConsultaDeReactivos");
        setMinimumSize(new java.awt.Dimension(900, 579));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                personalizarInterfaz(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jp1ConsultaReactivos.setBackground(new java.awt.Color(245, 245, 239));

        jp2InformacionReactivo.setBackground(new java.awt.Color(253, 251, 251));
        jp2InformacionReactivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del reactivo"));

        lab2Materia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab2Materia.setText("Materia:");

        lab3Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab3Grado.setText("Grado:");

        lab7Tema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab7Tema.setText("Tema:");

        cbox1Materia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox1Materia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción", "Matemáticas", "Español" }));
        cbox1Materia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscarMaterias(evt);
            }
        });
        cbox1Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaSeleccionada(evt);
            }
        });

        cbox2Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox2Grado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción", "3", "4", "5", "6" }));
        cbox2Grado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscarGrado(evt);
            }
        });
        cbox2Grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradoSeleccionado(evt);
            }
        });

        cbox3Tema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox3Tema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));

        lab1TotaldeReactivos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab1TotaldeReactivos.setText("Total de reactivos: #0");

        javax.swing.GroupLayout jp2InformacionReactivoLayout = new javax.swing.GroupLayout(jp2InformacionReactivo);
        jp2InformacionReactivo.setLayout(jp2InformacionReactivoLayout);
        jp2InformacionReactivoLayout.setHorizontalGroup(
            jp2InformacionReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2InformacionReactivoLayout.createSequentialGroup()
                .addGroup(jp2InformacionReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab2Materia)
                    .addComponent(lab7Tema))
                .addGap(18, 18, 18)
                .addGroup(jp2InformacionReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2InformacionReactivoLayout.createSequentialGroup()
                        .addComponent(cbox3Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp2InformacionReactivoLayout.createSequentialGroup()
                        .addComponent(cbox1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lab1TotaldeReactivos)
                        .addGap(35, 35, 35))))
            .addGroup(jp2InformacionReactivoLayout.createSequentialGroup()
                .addComponent(lab3Grado)
                .addGap(28, 28, 28)
                .addComponent(cbox2Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp2InformacionReactivoLayout.setVerticalGroup(
            jp2InformacionReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2InformacionReactivoLayout.createSequentialGroup()
                .addGroup(jp2InformacionReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab1TotaldeReactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jp2InformacionReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab3Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox2Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp2InformacionReactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab7Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox3Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp3Reactivos.setBackground(new java.awt.Color(253, 251, 251));
        jp3Reactivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Reactivos [Seleccione el reactivo para poder comentar o ver los comentarios]"));

        table1Reactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de lista", "Descripción del reactivo", "Respuesta correcta", "Respuesta Incorrecta 1", "Respuesta Incorrecta 2"
            }
        ));
        table1Reactivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarComentarios(evt);
            }
        });
        jScrollPane1.setViewportView(table1Reactivos);

        javax.swing.GroupLayout jp3ReactivosLayout = new javax.swing.GroupLayout(jp3Reactivos);
        jp3Reactivos.setLayout(jp3ReactivosLayout);
        jp3ReactivosLayout.setHorizontalGroup(
            jp3ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3ReactivosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jp3ReactivosLayout.setVerticalGroup(
            jp3ReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3ReactivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp5Comentario.setBackground(new java.awt.Color(253, 251, 251));
        jp5Comentario.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese un comentario"));

        txta1Comentario.setColumns(20);
        txta1Comentario.setRows(5);
        txta1Comentario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contarCaracteres(evt);
            }
        });
        jScrollPane2.setViewportView(txta1Comentario);

        lab4Caracteres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab4Caracteres.setText("Caracteres: 0");

        lab5MaximoCaracteres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab5MaximoCaracteres.setText("maximo 150 caracteres");

        javax.swing.GroupLayout jp5ComentarioLayout = new javax.swing.GroupLayout(jp5Comentario);
        jp5Comentario.setLayout(jp5ComentarioLayout);
        jp5ComentarioLayout.setHorizontalGroup(
            jp5ComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5ComentarioLayout.createSequentialGroup()
                .addComponent(lab5MaximoCaracteres)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jp5ComentarioLayout.createSequentialGroup()
                .addGroup(jp5ComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp5ComentarioLayout.createSequentialGroup()
                        .addComponent(lab4Caracteres)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp5ComentarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jp5ComentarioLayout.setVerticalGroup(
            jp5ComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5ComentarioLayout.createSequentialGroup()
                .addComponent(lab5MaximoCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab4Caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp4Comentarios.setBackground(new java.awt.Color(253, 251, 251));
        jp4Comentarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Comentarios"));

        table2Comentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de lista", "Numero de empleado", "Comentario", "Fecha"
            }
        ));
        jScrollPane4.setViewportView(table2Comentarios);

        lab6TotalComentarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab6TotalComentarios.setText("Total de comentarios: #0");

        javax.swing.GroupLayout jp4ComentariosLayout = new javax.swing.GroupLayout(jp4Comentarios);
        jp4Comentarios.setLayout(jp4ComentariosLayout);
        jp4ComentariosLayout.setHorizontalGroup(
            jp4ComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4ComentariosLayout.createSequentialGroup()
                .addGroup(jp4ComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4ComentariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lab6TotalComentarios)))
                .addContainerGap())
        );
        jp4ComentariosLayout.setVerticalGroup(
            jp4ComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4ComentariosLayout.createSequentialGroup()
                .addComponent(lab6TotalComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        boton3Salir.setBackground(new java.awt.Color(255, 255, 255));
        boton3Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton3Salir.setText("Salir");
        boton3Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        boton1Consultar.setBackground(new java.awt.Color(255, 255, 51));
        boton1Consultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton1Consultar.setText("Consultar");
        boton1Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar(evt);
            }
        });

        boton2Comentar.setBackground(new java.awt.Color(51, 204, 0));
        boton2Comentar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2Comentar.setText("Comentar");
        boton2Comentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comentar(evt);
            }
        });

        boton4Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        boton4Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton4Cancelar.setText("Cancelar");
        boton4Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        javax.swing.GroupLayout jp1ConsultaReactivosLayout = new javax.swing.GroupLayout(jp1ConsultaReactivos);
        jp1ConsultaReactivos.setLayout(jp1ConsultaReactivosLayout);
        jp1ConsultaReactivosLayout.setHorizontalGroup(
            jp1ConsultaReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1ConsultaReactivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1ConsultaReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton2Comentar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton4Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jp1ConsultaReactivosLayout.createSequentialGroup()
                        .addGroup(jp1ConsultaReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton1Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton3Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp1ConsultaReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp5Comentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp4Comentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp3Reactivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp2InformacionReactivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp1ConsultaReactivosLayout.setVerticalGroup(
            jp1ConsultaReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1ConsultaReactivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1ConsultaReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1ConsultaReactivosLayout.createSequentialGroup()
                        .addComponent(jp2InformacionReactivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp3Reactivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp4Comentarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1ConsultaReactivosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(boton1Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton4Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton3Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jp1ConsultaReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1ConsultaReactivosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp5Comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1ConsultaReactivosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton2Comentar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
        );

        jScrollPane3.setViewportView(jp1ConsultaReactivos);

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu1.setToolTipText("");
        menu1.add(jMenu1);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //[14] cierra la interfaz
    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {

            limpiarReactivos();
            limpiarComentarios();
            lab4Caracteres.setText("Caracteres: 0");
            lab6TotalComentarios.setText("Total de comentarios: #0");
            txta1Comentario.setText("");
            cbox1Materia.setSelectedIndex(0);
            cbox2Grado.setSelectedIndex(0);
            cbox3Tema.removeAllItems();
            cbox3Tema.addItem("Seleccione una opción");

            this.setVisible(false);

        }

    }//GEN-LAST:event_salir

    //[2] verifica si se ha seleccionado la materia
    private void materiaSeleccionada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaSeleccionada
        limpiarReactivos();
        limpiarComentarios();

        if (cbox1Materia.getSelectedIndex() != 0) {
            materiaSeleccionada = true;
            obtenerTemas();

        } else {
            materiaSeleccionada = false;
            obtenerTemas();

        }
        lab1TotaldeReactivos.setText("Total de reactivos: #0");
    }//GEN-LAST:event_materiaSeleccionada

    //[3] verifica si se ha seleccionado el grado
    private void gradoSeleccionado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradoSeleccionado
        limpiarReactivos();
        limpiarComentarios();

        if (cbox2Grado.getSelectedIndex() != 0) {
            gradoSeleccionado = true;
            obtenerTemas();

        } else {
            gradoSeleccionado = false;
            obtenerTemas();

        }
        lab1TotaldeReactivos.setText("Total de reactivos: #0");
    }//GEN-LAST:event_gradoSeleccionado

    //[5] busca los reactivos relacionados a la materia, tema y grado
    private void consultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar
        limpiarReactivos();
        limpiarComentarios();
        lab1TotaldeReactivos.setText("Total de reactivos: #0");
        if (cbox1Materia.getSelectedIndex() != 0 && cbox2Grado.getSelectedIndex() != 0) {

            table1Reactivos.removeAll();
            ControlReactivo reactivo = new ControlReactivo();

            try {
                System.out.println(cbox1Materia.getSelectedIndex() + " " + cbox3Tema.getItemAt(cbox3Tema.getSelectedIndex()).toString() + " " + (cbox2Grado.getSelectedIndex() + 2));
                ResultSet consultar = reactivo.consultarReactivos(cbox1Materia.getSelectedIndex(), cbox3Tema.getItemAt(cbox3Tema.getSelectedIndex()).toString(), (cbox2Grado.getSelectedIndex() + 2));

                llenarReactivos(consultar);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazConsultaDeReactivos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "SELECCIONA LA MATERIA Y EL GRADO", "ERROR", JOptionPane.ERROR_MESSAGE);
            table1Reactivos.removeAll();
        }
    }//GEN-LAST:event_consultar

    //[7] busca las comentarios relacionados a un reactivo
    private void buscarComentarios(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarComentarios
        ControlComentario comentario = new ControlComentario();

        try {
            limpiarComentarios();
            String reactivo = table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 1).toString();
            ResultSet[] resultados = comentario.consultar(reactivo);
            llenarComentarios(resultados);
        } catch (NullPointerException | ArrayIndexOutOfBoundsException e) {
            System.out.println(e);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_buscarComentarios

    //[9] cuenta el total de caracteres del comentario
    private void contarCaracteres(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contarCaracteres
        int totaldeCaracteres = txta1Comentario.getText().length();
        lab4Caracteres.setText("Caracteres: " + totaldeCaracteres);
        if (totaldeCaracteres > 150) {
            lab4Caracteres.setForeground(Color.red);

        } else {
            lab4Caracteres.setForeground(Color.black);
        }


    }//GEN-LAST:event_contarCaracteres

    //[1]asigna el nombre y el id del usuario a la interfaz
    private void personalizarInterfaz(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_personalizarInterfaz
        jMenu1.setText("Mi cuenta: " + nombre + " : " + idUsuario);
    }//GEN-LAST:event_personalizarInterfaz

    //[10] permite ingresar un comentario a un reactivo en especifico
    private void comentar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comentar
        limpiarComentarios();
        this.buscarComentarios(null);
        if (txta1Comentario.getText().length() > 5 && txta1Comentario.getText().length() <= 150) {
            ControlComentario comentario = new ControlComentario();
            try {
                comentario.registrar(txta1Comentario.getText(), table1Reactivos.getValueAt(table1Reactivos.getSelectedRow(), 1).toString(), idUsuario);
                JOptionPane.showMessageDialog(rootPane, "COMENTARIO REGISTRADO", "FELICIDADES", JOptionPane.WARNING_MESSAGE);

            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, "SELECCIONE UN REACTIVO", "ERROR", JOptionPane.WARNING_MESSAGE);
            } catch (ArrayIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(rootPane, "SELECCIONE UN REACTIVO", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            txta1Comentario.setText("");
            MouseEvent MouseEvent = null;
            buscarComentarios(MouseEvent);
            lab4Caracteres.setText("Caracteres: 0");
        } else {
            String mensaje = "";
            if (txta1Comentario.getText().length() < 5) {
                mensaje = "Comentario demaciado corto";
            } else if (txta1Comentario.getText().length() > 150) {
                mensaje = "Comentario demaciado largo";
            }
            JOptionPane.showMessageDialog(rootPane, "" + mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_comentar

    //[11] limpia todos los campos de la interfaz
    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        limpiarReactivos();
        limpiarComentarios();
        lab4Caracteres.setText("Caracteres: 0");
        lab6TotalComentarios.setText("Total de comentarios: #0");
        txta1Comentario.setText("");
        cbox1Materia.setSelectedIndex(0);
        cbox2Grado.setSelectedIndex(0);
        cbox3Tema.removeAllItems();
        cbox3Tema.addItem("Seleccione una opción");

    }//GEN-LAST:event_cancelar

    public void limpiarCampos() {

        cbox1Materia.removeAllItems();
        cbox1Materia.addItem("Seleccione una opción");

        cbox2Grado.removeAllItems();
        cbox2Grado.addItem("Seleccione una opción");

        cbox3Tema.removeAllItems();
        cbox3Tema.addItem("Seleccione una opción");
        limpiarReactivos();
        limpiarComentarios();

    }

    private void buscarMaterias(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarMaterias
        // TODO add your handling code here:
        limpiarCampos();
        ControlMateria cMateria = new ControlMateria();
        try {
            ResultSet obtenerMaterias = cMateria.obtenerMaterias();

            while (obtenerMaterias.next()) {
                cbox1Materia.addItem(obtenerMaterias.getObject(1));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_buscarMaterias

    private void buscarGrado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarGrado
        // TODO add your handling code here:
        ControlGrupo Cgrupo = new ControlGrupo();
        try {
            ResultSet obtenerGrados = Cgrupo.obtenerGrupos();

            String grado = "";

            while (obtenerGrados.next()) {
                grado = obtenerGrados.getObject(1).toString();
                int totalGrado = cbox2Grado.getItemCount();
                int maximo = 0;

                for (int i = 0; i < totalGrado; i++) {
                    if (grado.compareTo(cbox2Grado.getItemAt(i).toString()) == 0) {
                        maximo++;

                    }
                }
                if (maximo == 0) {
                    this.cbox2Grado.addItem(grado);
                }

            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error al intentar obtener datos a la bd");
        }

    }//GEN-LAST:event_buscarGrado

    //[8]muestra los comentario segun el reactivo seleccionado
    public void llenarComentarios(ResultSet conjuntoResultados[]) throws SQLException {
        int posicion = 0;
        DefaultTableModel modelo = (DefaultTableModel) table2Comentarios.getModel();

        while (conjuntoResultados[1].next()) {
            modelo.addRow(new Object[]{
                "",
                conjuntoResultados[1].getObject(1).toString(),
                "",
                ""
            });

            posicion++;
        }

        posicion = 0;
        while (conjuntoResultados[0].next()) {
            table2Comentarios.setValueAt((posicion + 1), posicion, 0);
            table2Comentarios.setValueAt(conjuntoResultados[0].getObject(1).toString(), posicion, 2);
            table2Comentarios.setValueAt(conjuntoResultados[0].getObject(2).toString(), posicion, 3);

            posicion++;
        }

        contarTotalComentario = posicion;
        lab6TotalComentarios.setText("Total de comentarios: #" + contarTotalComentario);

    }

    //[6] muestra los reactivos encontrados
    public void llenarReactivos(ResultSet conjuntoResultados) throws ClassNotFoundException, SQLException {
        table1Reactivos.removeAll();

        DefaultTableModel modelo = (DefaultTableModel) table1Reactivos.getModel();

        int posicion = 0;
        while (conjuntoResultados.next()) {
            modelo.addRow(new Object[]{
                (posicion + 1),
                conjuntoResultados.getObject(1).toString(),
                conjuntoResultados.getObject(2).toString(),
                conjuntoResultados.getObject(3).toString(),
                conjuntoResultados.getObject(4).toString(),});

            posicion++;

        }//find el while
        contarTotalReactivos = posicion;
        lab1TotaldeReactivos.setText("Total de reactivos: #" + contarTotalReactivos);

    }

    //[12] remueve la tabla de los reactivos
    public void limpiarReactivos() {
        // TODO add your handling code here:
        try {

            DefaultTableModel modelo = (DefaultTableModel) table1Reactivos.getModel();
            int total = table1Reactivos.getRowCount();
            for (int i = 0; i < total; i++) {
                modelo.removeRow(0);
            }

        } catch (NumberFormatException e) {
            System.out.println(e.toString());
        }

    }

    //[13] remueve la tabla de los comentarios
    public void limpiarComentarios() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) table2Comentarios.getModel();
            int total = table2Comentarios.getRowCount();
            for (int i = 0; i < total; i++) {
                modelo.removeRow(0);
            }

        } catch (NumberFormatException e) {
            System.out.println(e.toString());
        }

    }

    //[4] obtiene y muestra los temas en relacion a la materia y grado
    public void obtenerTemas() {
        cbox3Tema.removeAllItems();
        cbox3Tema.addItem("Seleccione una opción");
        ControlTema temaC = new ControlTema();
        if (materiaSeleccionada && gradoSeleccionado) {
            try {

                ResultSet resultado = temaC.consultarTemas((cbox1Materia.getSelectedIndex()), (cbox2Grado.getSelectedIndex() + 2));

                while (resultado.next()) {

                    cbox3Tema.addItem(resultado.getObject(1));

                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazConsultaDeReactivos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            cbox3Tema.removeAllItems();
            cbox3Tema.addItem("Seleccione una opción");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaDeReactivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaDeReactivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaDeReactivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaDeReactivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConsultaDeReactivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1Consultar;
    private javax.swing.JButton boton2Comentar;
    private javax.swing.JButton boton3Salir;
    private javax.swing.JButton boton4Cancelar;
    private javax.swing.JComboBox cbox1Materia;
    private javax.swing.JComboBox cbox2Grado;
    private javax.swing.JComboBox cbox3Tema;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jp1ConsultaReactivos;
    private javax.swing.JPanel jp2InformacionReactivo;
    private javax.swing.JPanel jp3Reactivos;
    private javax.swing.JPanel jp4Comentarios;
    private javax.swing.JPanel jp5Comentario;
    private javax.swing.JLabel lab1TotaldeReactivos;
    private javax.swing.JLabel lab2Materia;
    private javax.swing.JLabel lab3Grado;
    private javax.swing.JLabel lab4Caracteres;
    private javax.swing.JLabel lab5MaximoCaracteres;
    private javax.swing.JLabel lab6TotalComentarios;
    private javax.swing.JLabel lab7Tema;
    private javax.swing.JMenuBar menu1;
    private javax.swing.JTable table1Reactivos;
    private javax.swing.JTable table2Comentarios;
    private javax.swing.JTextArea txta1Comentario;
    // End of variables declaration//GEN-END:variables
}
