/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteMantenimientoUsuarios;

import PaqueteLogin.InterfazLogin;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazConsultaEspecificaAlumno extends javax.swing.JFrame {

    String totaldeAlumnos;

    /**
     * Creates new form Alumnos
     */
    public InterfazConsultaEspecificaAlumno() throws ClassNotFoundException, SQLException {
        initComponents();
        //establece la posicion central de la interfaz
        this.setLocationRelativeTo(null);

        //colocar el icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        //cuenta el total de alumnos que existen en la base de datos
        contarAlumnos();

        //limpia todos los campos
        limpiarCampos();

        //asigna la palabra administrador a la interfaz
        jMenu1.setText("Mi cuenta: ADMINISTRADOR");

        //des activa la opcion maximizar 
        this.setResizable(false);
        //desactiva la opcion cerrar
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp2EliminarMaestro = new javax.swing.JPanel();
        boton3Salir = new javax.swing.JButton();
        lab1TotaldeAlumnos = new javax.swing.JLabel();
        boton1Buscar = new javax.swing.JButton();
        jp1IngresoDatosdelMaestro = new javax.swing.JPanel();
        lab2IngresoNumeroEmpleado = new javax.swing.JLabel();
        txt1IngresoMatricula = new javax.swing.JTextField();
        jp3DatosAlumno = new javax.swing.JPanel();
        lab4NumeroEmpleado = new javax.swing.JLabel();
        lab5NombreMaestro = new javax.swing.JLabel();
        lab6ApellidoPaterno = new javax.swing.JLabel();
        lab12ApellidoMaterno = new javax.swing.JLabel();
        txt5ApellidoMaterno = new javax.swing.JTextField();
        txt4ApellidoPaterno = new javax.swing.JTextField();
        txt3NombreAlumno = new javax.swing.JTextField();
        txt2Matricula = new javax.swing.JTextField();
        jp4DatosGrupo = new javax.swing.JPanel();
        lab9Grupo = new javax.swing.JLabel();
        lab8Grado = new javax.swing.JLabel();
        txt6Grado = new javax.swing.JTextField();
        txt7Grupo = new javax.swing.JTextField();
        jp5DatosUsuario = new javax.swing.JPanel();
        lab10Usuario = new javax.swing.JLabel();
        lab11Contraseña = new javax.swing.JLabel();
        txt9Contraseña = new javax.swing.JTextField();
        txt8Usuario = new javax.swing.JTextField();
        boton2Cancelar = new javax.swing.JButton();
        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MantenimientoUsuarios/ConsultarUsuarios/ConsultaEspecificaAlumno");

        jp2EliminarMaestro.setBackground(new java.awt.Color(245, 245, 239));
        jp2EliminarMaestro.setToolTipText("");

        boton3Salir.setBackground(new java.awt.Color(255, 255, 255));
        boton3Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton3Salir.setText("Salir");
        boton3Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        lab1TotaldeAlumnos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab1TotaldeAlumnos.setText("Total de alumnos registrados: #00");

        boton1Buscar.setBackground(new java.awt.Color(255, 255, 51));
        boton1Buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton1Buscar.setText("Buscar");
        boton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        jp1IngresoDatosdelMaestro.setBackground(new java.awt.Color(253, 251, 251));
        jp1IngresoDatosdelMaestro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matricula", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lab2IngresoNumeroEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab2IngresoNumeroEmpleado.setText("Ingrese la matricula:");

        txt1IngresoMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jp1IngresoDatosdelMaestroLayout = new javax.swing.GroupLayout(jp1IngresoDatosdelMaestro);
        jp1IngresoDatosdelMaestro.setLayout(jp1IngresoDatosdelMaestroLayout);
        jp1IngresoDatosdelMaestroLayout.setHorizontalGroup(
            jp1IngresoDatosdelMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1IngresoDatosdelMaestroLayout.createSequentialGroup()
                .addComponent(lab2IngresoNumeroEmpleado)
                .addGap(18, 18, 18)
                .addComponent(txt1IngresoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp1IngresoDatosdelMaestroLayout.setVerticalGroup(
            jp1IngresoDatosdelMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1IngresoDatosdelMaestroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jp1IngresoDatosdelMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2IngresoNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1IngresoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jp3DatosAlumno.setBackground(new java.awt.Color(253, 251, 251));
        jp3DatosAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del alumno"));

        lab4NumeroEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab4NumeroEmpleado.setText("Matricula:");

        lab5NombreMaestro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab5NombreMaestro.setText("Nombre del alumno:");

        lab6ApellidoPaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab6ApellidoPaterno.setText("Apellido paterno:");

        lab12ApellidoMaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab12ApellidoMaterno.setText("Apellido materno:");

        txt5ApellidoMaterno.setEditable(false);

        txt4ApellidoPaterno.setEditable(false);

        txt3NombreAlumno.setEditable(false);

        txt2Matricula.setEditable(false);

        javax.swing.GroupLayout jp3DatosAlumnoLayout = new javax.swing.GroupLayout(jp3DatosAlumno);
        jp3DatosAlumno.setLayout(jp3DatosAlumnoLayout);
        jp3DatosAlumnoLayout.setHorizontalGroup(
            jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3DatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab4NumeroEmpleado)
                    .addComponent(lab6ApellidoPaterno)
                    .addComponent(lab12ApellidoMaterno)
                    .addComponent(lab5NombreMaestro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt2Matricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt3NombreAlumno)
                        .addComponent(txt4ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt5ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp3DatosAlumnoLayout.setVerticalGroup(
            jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3DatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp3DatosAlumnoLayout.createSequentialGroup()
                        .addComponent(txt2Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt3NombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp3DatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lab4NumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab5NombreMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab6ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab12ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jp4DatosGrupo.setBackground(new java.awt.Color(253, 251, 251));
        jp4DatosGrupo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del grupo"));

        lab9Grupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab9Grupo.setText("Grupo Asignado:");

        lab8Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab8Grado.setText("Grado Asignado:");

        txt6Grado.setEditable(false);

        txt7Grupo.setEditable(false);

        javax.swing.GroupLayout jp4DatosGrupoLayout = new javax.swing.GroupLayout(jp4DatosGrupo);
        jp4DatosGrupo.setLayout(jp4DatosGrupoLayout);
        jp4DatosGrupoLayout.setHorizontalGroup(
            jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4DatosGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab8Grado)
                    .addComponent(lab9Grupo))
                .addGap(32, 32, 32)
                .addGroup(jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt7Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jp4DatosGrupoLayout.setVerticalGroup(
            jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4DatosGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp4DatosGrupoLayout.createSequentialGroup()
                        .addComponent(txt6Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt7Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp4DatosGrupoLayout.createSequentialGroup()
                        .addComponent(lab8Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab9Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jp5DatosUsuario.setBackground(new java.awt.Color(253, 251, 251));
        jp5DatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        lab10Usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab10Usuario.setText("Usuario:");

        lab11Contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab11Contraseña.setText("Contraseña:");

        txt9Contraseña.setEditable(false);

        txt8Usuario.setEditable(false);

        javax.swing.GroupLayout jp5DatosUsuarioLayout = new javax.swing.GroupLayout(jp5DatosUsuario);
        jp5DatosUsuario.setLayout(jp5DatosUsuarioLayout);
        jp5DatosUsuarioLayout.setHorizontalGroup(
            jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5DatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp5DatosUsuarioLayout.createSequentialGroup()
                        .addComponent(lab10Usuario)
                        .addGap(84, 84, 84)
                        .addComponent(txt8Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5DatosUsuarioLayout.createSequentialGroup()
                        .addComponent(lab11Contraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt9Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp5DatosUsuarioLayout.setVerticalGroup(
            jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5DatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab10Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt8Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab11Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt9Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        boton2Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        boton2Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2Cancelar.setText("Cancelar");
        boton2Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        javax.swing.GroupLayout jp2EliminarMaestroLayout = new javax.swing.GroupLayout(jp2EliminarMaestro);
        jp2EliminarMaestro.setLayout(jp2EliminarMaestroLayout);
        jp2EliminarMaestroLayout.setHorizontalGroup(
            jp2EliminarMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2EliminarMaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp2EliminarMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp2EliminarMaestroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lab1TotaldeAlumnos)
                        .addGap(58, 58, 58))
                    .addGroup(jp2EliminarMaestroLayout.createSequentialGroup()
                        .addGroup(jp2EliminarMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton3Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton1Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton2Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp2EliminarMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp1IngresoDatosdelMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp3DatosAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp4DatosGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp5DatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(147, 147, 147))))
        );
        jp2EliminarMaestroLayout.setVerticalGroup(
            jp2EliminarMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2EliminarMaestroLayout.createSequentialGroup()
                .addComponent(lab1TotaldeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jp2EliminarMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2EliminarMaestroLayout.createSequentialGroup()
                        .addComponent(jp1IngresoDatosdelMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp3DatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp4DatosGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jp5DatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2EliminarMaestroLayout.createSequentialGroup()
                        .addComponent(boton1Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton2Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton3Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu1.setText("Mi cuenta");
        jMenu1.setToolTipText("");
        menu1.add(jMenu1);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp2EliminarMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp2EliminarMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //[5] limpia campos y oculta la interfaz
    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        // TODO add your handling code here:
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {
            limpiarCampos();
            this.setVisible(false);

        }
    }//GEN-LAST:event_salir

    //[3] busca y muestra la informacion del alumno con respecto a la matricula ingresada
    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        //variables para poder saber si todo esta correcto
        boolean matriculaCorrecto = false;
        if (txt1IngresoMatricula.getText().length() != 0) {

            //identificar si el numero del maestro es correcto
            try {
                if (Integer.parseInt(txt1IngresoMatricula.getText()) > 0) {
                    matriculaCorrecto = true;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "MATRICULA INCORRECTA", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            if (matriculaCorrecto == true) {

                ControlAlumno alumnoC = new ControlAlumno();
                ControlGrupo grupoC = new ControlGrupo();
                ControlUsuario usuarioC = new ControlUsuario();
                try {

                    ResultSet resultadodeConsultar = alumnoC.consultar(txt1IngresoMatricula.getText());

                    while (resultadodeConsultar.next()) {

                        txt2Matricula.setText(resultadodeConsultar.getObject(1).toString());
                        txt3NombreAlumno.setText(resultadodeConsultar.getObject(2).toString());
                        txt4ApellidoPaterno.setText(resultadodeConsultar.getObject(3).toString());
                        txt5ApellidoMaterno.setText(resultadodeConsultar.getObject(4).toString());

                    }//find el while

                    //cuando no se ha encontrado al maestro
                    if (txt2Matricula.getText().length() <= 0
                            && txt3NombreAlumno.getText().length() <= 0
                            && txt4ApellidoPaterno.getText().length() <= 0
                            && txt5ApellidoMaterno.getText().length() <= 0) {
                        JOptionPane.showMessageDialog(rootPane, "LA MATRICULA NO SE ENCUENTRA", "ERROR", JOptionPane.ERROR_MESSAGE);

                    }

                    //obtener informacion del Grupo
                    resultadodeConsultar = grupoC.consultarGrupodeAlumno(txt1IngresoMatricula.getText());
                    while (resultadodeConsultar.next()) {
                        txt6Grado.setText(resultadodeConsultar.getObject(1).toString());
                        txt7Grupo.setText(resultadodeConsultar.getObject(2).toString());
                    }//find el while

                    //obtener informacion del usuario
                    resultadodeConsultar = usuarioC.consultar(txt1IngresoMatricula.getText(), "alumno");
                    while (resultadodeConsultar.next()) {
                        txt8Usuario.setText(resultadodeConsultar.getObject(1).toString());
                        txt9Contraseña.setText(resultadodeConsultar.getObject(2).toString());
                    }//find el while

                } catch (SQLException | ClassNotFoundException ex) {

                    Logger.getLogger(InterfazConsultaEspecificaAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }

                //contar el actualizado de maestros
                try {
                    contarAlumnos();
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(InterfazConsultaEspecificaAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        } else {
            String mensaje = "";

            if (txt1IngresoMatricula.getText().length() <= 0) {
                mensaje = "-Matricula\n";
            }

            JOptionPane.showMessageDialog(rootPane, "INGRESE EL SIGUIENTE CAMPO:\n" + mensaje + "", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_buscar

    //[4] limpia todos los campos de la interfaz
    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        limpiarCampos();
    }//GEN-LAST:event_cancelar

    //[1] cuenta el total de alumnos en la base de datos
    public void contarAlumnos() throws ClassNotFoundException, SQLException {
        ControlAlumno alumno = new ControlAlumno();
        totaldeAlumnos = alumno.contarTotalAlumnos();
        lab1TotaldeAlumnos.setText("Total de alumnos registrados: #" + (totaldeAlumnos));
    }

    //[2] limpia todos los campos existentes en la base de datos
    public void limpiarCampos() {
        txt2Matricula.setText("");
        txt3NombreAlumno.setText("");
        txt4ApellidoPaterno.setText("");
        txt5ApellidoMaterno.setText("");
        txt6Grado.setText("");
        txt7Grupo.setText("");
        txt8Usuario.setText("");
        txt9Contraseña.setText("");
        txt1IngresoMatricula.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaEspecificaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaEspecificaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaEspecificaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaEspecificaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazConsultaEspecificaAlumno().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(InterfazConsultaEspecificaAlumno.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(InterfazConsultaEspecificaAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1Buscar;
    private javax.swing.JButton boton2Cancelar;
    private javax.swing.JButton boton3Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jp1IngresoDatosdelMaestro;
    private javax.swing.JPanel jp2EliminarMaestro;
    private javax.swing.JPanel jp3DatosAlumno;
    private javax.swing.JPanel jp4DatosGrupo;
    private javax.swing.JPanel jp5DatosUsuario;
    private javax.swing.JLabel lab10Usuario;
    private javax.swing.JLabel lab11Contraseña;
    private javax.swing.JLabel lab12ApellidoMaterno;
    private javax.swing.JLabel lab1TotaldeAlumnos;
    private javax.swing.JLabel lab2IngresoNumeroEmpleado;
    private javax.swing.JLabel lab4NumeroEmpleado;
    private javax.swing.JLabel lab5NombreMaestro;
    private javax.swing.JLabel lab6ApellidoPaterno;
    private javax.swing.JLabel lab8Grado;
    private javax.swing.JLabel lab9Grupo;
    private javax.swing.JMenuBar menu1;
    private javax.swing.JTextField txt1IngresoMatricula;
    private javax.swing.JTextField txt2Matricula;
    private javax.swing.JTextField txt3NombreAlumno;
    private javax.swing.JTextField txt4ApellidoPaterno;
    private javax.swing.JTextField txt5ApellidoMaterno;
    private javax.swing.JTextField txt6Grado;
    private javax.swing.JTextField txt7Grupo;
    private javax.swing.JTextField txt8Usuario;
    private javax.swing.JTextField txt9Contraseña;
    // End of variables declaration//GEN-END:variables
}
