/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteMantenimientoUsuarios;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazEliminarAlumno extends javax.swing.JFrame {

    String totaldeAlumnos;

    /**
     * Creates new form InterfazEliminarAlumno
     */
    public InterfazEliminarAlumno() throws ClassNotFoundException, SQLException {
        initComponents();
        //establece la posicion central de la interfaz
        this.setLocationRelativeTo(null);

        //coloca el icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        //cuenta el total de alumnos
        contarAlumnos();
        //limpia los campos
        limpiarCampos();
        //establece el nombre de administrados en la interfaz
        jMenu1.setText("Mi cuenta: ADMINISTRADOR");

        //activa el boton buscar y des activa el boton eliminar
        boton1Buscar.setEnabled(true);
        boton2Eliminar.setEnabled(false);

        //des activa la opcion maximizar 
        this.setResizable(false);
        //desactiva la opcion cerrar
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1EliminarAlumno = new javax.swing.JPanel();
        boton3Salir = new javax.swing.JButton();
        boton2Eliminar = new javax.swing.JButton();
        lab1TotaldeAlumnos = new javax.swing.JLabel();
        boton1Buscar = new javax.swing.JButton();
        jp2Matricula = new javax.swing.JPanel();
        lab2IngresoMatricula = new javax.swing.JLabel();
        txt1IngresoMatricula = new javax.swing.JTextField();
        jp3DatosAlumno = new javax.swing.JPanel();
        txt5ApellidoMaterno = new javax.swing.JTextField();
        lab6ApellidoMaterno = new javax.swing.JLabel();
        lab5ApellidoPaterno = new javax.swing.JLabel();
        lab4NombreAlumno = new javax.swing.JLabel();
        lab3Matricula = new javax.swing.JLabel();
        txt2Matricula = new javax.swing.JTextField();
        txt3NombreAlumno = new javax.swing.JTextField();
        txt4ApellidoPaterno = new javax.swing.JTextField();
        jp4DatosGrupo = new javax.swing.JPanel();
        txt7Grupo = new javax.swing.JTextField();
        txt6Grado = new javax.swing.JTextField();
        lab7Grado = new javax.swing.JLabel();
        lab8Grupo = new javax.swing.JLabel();
        jp5DatosUsuario = new javax.swing.JPanel();
        txt8Usuario = new javax.swing.JTextField();
        txt9Contraseña = new javax.swing.JTextField();
        lab9Usuario = new javax.swing.JLabel();
        lab10Contraseña = new javax.swing.JLabel();
        boton4Cancelar = new javax.swing.JButton();
        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento Usuario/Eliminar Usuario/Eliminar Alumno");
        setMinimumSize(new java.awt.Dimension(596, 534));
        setResizable(false);

        jp1EliminarAlumno.setBackground(new java.awt.Color(245, 245, 239));
        jp1EliminarAlumno.setToolTipText("");

        boton3Salir.setBackground(new java.awt.Color(255, 255, 255));
        boton3Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton3Salir.setText("Salir");
        boton3Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        boton2Eliminar.setBackground(new java.awt.Color(51, 204, 0));
        boton2Eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2Eliminar.setText("Eliminar");
        boton2Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar(evt);
            }
        });

        lab1TotaldeAlumnos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab1TotaldeAlumnos.setText("Total de alumnos registrados: #00");

        boton1Buscar.setBackground(new java.awt.Color(255, 255, 51));
        boton1Buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton1Buscar.setText("Buscar");
        boton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        jp2Matricula.setBackground(new java.awt.Color(253, 251, 251));
        jp2Matricula.setBorder(javax.swing.BorderFactory.createTitledBorder("Matricula"));

        lab2IngresoMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab2IngresoMatricula.setText("Ingrese la matricula:");

        txt1IngresoMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jp2MatriculaLayout = new javax.swing.GroupLayout(jp2Matricula);
        jp2Matricula.setLayout(jp2MatriculaLayout);
        jp2MatriculaLayout.setHorizontalGroup(
            jp2MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2MatriculaLayout.createSequentialGroup()
                .addComponent(lab2IngresoMatricula)
                .addGap(84, 84, 84)
                .addComponent(txt1IngresoMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );
        jp2MatriculaLayout.setVerticalGroup(
            jp2MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2MatriculaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp2MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2IngresoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1IngresoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jp3DatosAlumno.setBackground(new java.awt.Color(253, 251, 251));
        jp3DatosAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del alumno"));

        txt5ApellidoMaterno.setEditable(false);

        lab6ApellidoMaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab6ApellidoMaterno.setText("Apellido materno:");

        lab5ApellidoPaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab5ApellidoPaterno.setText("Apellido paterno:");

        lab4NombreAlumno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab4NombreAlumno.setText("Nombre del alumno:");

        lab3Matricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab3Matricula.setText("Matricula:");

        txt2Matricula.setEditable(false);

        txt3NombreAlumno.setEditable(false);

        txt4ApellidoPaterno.setEditable(false);

        javax.swing.GroupLayout jp3DatosAlumnoLayout = new javax.swing.GroupLayout(jp3DatosAlumno);
        jp3DatosAlumno.setLayout(jp3DatosAlumnoLayout);
        jp3DatosAlumnoLayout.setHorizontalGroup(
            jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3DatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp3DatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lab3Matricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt2Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3DatosAlumnoLayout.createSequentialGroup()
                        .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab5ApellidoPaterno)
                            .addComponent(lab4NombreAlumno))
                        .addGap(4, 4, Short.MAX_VALUE)
                        .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt3NombreAlumno)
                            .addComponent(txt4ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp3DatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lab6ApellidoMaterno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt5ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp3DatosAlumnoLayout.setVerticalGroup(
            jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3DatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab3Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab4NombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3NombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab5ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt4ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp3DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab6ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jp4DatosGrupo.setBackground(new java.awt.Color(253, 251, 251));
        jp4DatosGrupo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del grupo"));

        txt7Grupo.setEditable(false);

        txt6Grado.setEditable(false);

        lab7Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab7Grado.setText("Grado Asignado:");

        lab8Grupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab8Grupo.setText("Grupo Asignado:");

        javax.swing.GroupLayout jp4DatosGrupoLayout = new javax.swing.GroupLayout(jp4DatosGrupo);
        jp4DatosGrupo.setLayout(jp4DatosGrupoLayout);
        jp4DatosGrupoLayout.setHorizontalGroup(
            jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4DatosGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab7Grado)
                    .addComponent(lab8Grupo))
                .addGap(27, 27, 27)
                .addGroup(jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt7Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp4DatosGrupoLayout.setVerticalGroup(
            jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4DatosGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab7Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp4DatosGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab8Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt7Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jp5DatosUsuario.setBackground(new java.awt.Color(253, 251, 251));
        jp5DatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        txt8Usuario.setEditable(false);

        txt9Contraseña.setEditable(false);

        lab9Usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab9Usuario.setText("Usuario:");

        lab10Contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab10Contraseña.setText("Contraseña:");

        javax.swing.GroupLayout jp5DatosUsuarioLayout = new javax.swing.GroupLayout(jp5DatosUsuario);
        jp5DatosUsuario.setLayout(jp5DatosUsuarioLayout);
        jp5DatosUsuarioLayout.setHorizontalGroup(
            jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5DatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab9Usuario)
                    .addComponent(lab10Contraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt8Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt9Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jp5DatosUsuarioLayout.setVerticalGroup(
            jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5DatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab9Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt8Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab10Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt9Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        boton4Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        boton4Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton4Cancelar.setText("Cancelar");
        boton4Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        javax.swing.GroupLayout jp1EliminarAlumnoLayout = new javax.swing.GroupLayout(jp1EliminarAlumno);
        jp1EliminarAlumno.setLayout(jp1EliminarAlumnoLayout);
        jp1EliminarAlumnoLayout.setHorizontalGroup(
            jp1EliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1EliminarAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1EliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp1EliminarAlumnoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lab1TotaldeAlumnos)
                        .addGap(6, 6, 6))
                    .addGroup(jp1EliminarAlumnoLayout.createSequentialGroup()
                        .addGroup(jp1EliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton2Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(boton3Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton1Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton4Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp1EliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp5DatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp4DatosGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp3DatosAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp2Matricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(58, 58, 58))
        );
        jp1EliminarAlumnoLayout.setVerticalGroup(
            jp1EliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1EliminarAlumnoLayout.createSequentialGroup()
                .addComponent(lab1TotaldeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jp1EliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1EliminarAlumnoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(boton1Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton2Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton4Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton3Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1EliminarAlumnoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jp2Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jp3DatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jp4DatosGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp5DatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu1.setText("Mi cuenta");
        jMenu1.setToolTipText("");
        menu1.add(jMenu1);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1EliminarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1EliminarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //[6] cierra la interfaz
    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {
            limpiarCampos();
            txt1IngresoMatricula.setText("");
            boton1Buscar.setEnabled(true);
            boton2Eliminar.setEnabled(false);
            this.setVisible(false);

        }
    }//GEN-LAST:event_salir

    //[4] elimina el alumno indicado
    private void eliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar
        if (txt2Matricula.getText().length() != 0
                && txt3NombreAlumno.getText().length() != 0
                && txt4ApellidoPaterno.getText().length() != 0
                && txt5ApellidoMaterno.getText().length() != 0
                && txt6Grado.getText().length() != 0
                && txt7Grupo.getText().length() != 0
                && txt8Usuario.getText().length() != 0
                && txt9Contraseña.getText().length() != 0) {

            int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA ELIMINAR?");
            if (salir == 0) {

                boton1Buscar.setEnabled(true);
                boton2Eliminar.setEnabled(false);

                ControlAlumno alumnoC = new ControlAlumno();
                ControlUsuario usuarioC = new ControlUsuario();
                ControlGrupo grupoC = new ControlGrupo();

                try {
                     alumnoC.eliminar(txt2Matricula.getText());
                     grupoC.eliminarAlumnodelGrupo(txt2Matricula.getText());
                    usuarioC.eliminar(txt2Matricula.getText());
                    
                   
                    JOptionPane.showMessageDialog(rootPane, "ELIMINACION EXITOSA", "FELICIDADES", JOptionPane.WARNING_MESSAGE);

                } catch (SQLException ex) {
                    Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }

                //limpia campos
                limpiarCampos();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "DEBE ELEGIR A UN ALUMNO ANTES PARA ELIMINAR ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_eliminar

    //[3] busca la informacion del alumno indicado
    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        //limpiar todos los campos
        limpiarCampos();

        //variables para poder saber si todo esta correcto 
        boolean matriculaCorrecto = false;
        if (txt1IngresoMatricula.getText().length() != 0) {

            //identificar si el numero del maestro es correcto
            try {
                if (Integer.parseInt(txt1IngresoMatricula.getText()) > 0) {
                    matriculaCorrecto = true;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "MATRICULA INCORRECTA", "ERROR", JOptionPane.ERROR_MESSAGE);
                boton1Buscar.setEnabled(true);
                boton2Eliminar.setEnabled(false);
            }

            if (matriculaCorrecto == true) {
                boton1Buscar.setEnabled(false);
                boton2Eliminar.setEnabled(true);
                ControlAlumno alumnoC = new ControlAlumno();
                ControlGrupo grupoC = new ControlGrupo();
                ControlUsuario usuarioC = new ControlUsuario();
                try {

                    //obtener de maestro
                    ResultSet resultadodeConsultar = alumnoC.consultar(txt1IngresoMatricula.getText());

                    while (resultadodeConsultar.next()) {

                        txt2Matricula.setText(resultadodeConsultar.getObject(1).toString());
                        txt3NombreAlumno.setText(resultadodeConsultar.getObject(2).toString());
                        txt4ApellidoPaterno.setText(resultadodeConsultar.getObject(3).toString());
                        txt5ApellidoMaterno.setText(resultadodeConsultar.getObject(4).toString());

                    }//find el while

                    //cuando no se ha encontrado al maestro
                    if (txt2Matricula.getText().length() <= 0
                            && txt3NombreAlumno.getText().length() <= 0
                            && txt4ApellidoPaterno.getText().length() <= 0
                            && txt5ApellidoMaterno.getText().length() <= 0) {
                        JOptionPane.showMessageDialog(rootPane, "LA MATRICULA NO SE ENCUENTRA", "ERROR", JOptionPane.ERROR_MESSAGE);
                        boton1Buscar.setEnabled(true);
                        boton2Eliminar.setEnabled(false);
                    }

                    //obtener informacion del Grupo
                    resultadodeConsultar = grupoC.consultarGrupodeAlumno(txt1IngresoMatricula.getText());
                    while (resultadodeConsultar.next()) {
                        txt6Grado.setText(resultadodeConsultar.getObject(1).toString());
                        txt7Grupo.setText(resultadodeConsultar.getObject(2).toString());
                    }//find el while

                    //obtener informacion del usuario
                    resultadodeConsultar = usuarioC.consultar(txt1IngresoMatricula.getText(), "alumno");
                    while (resultadodeConsultar.next()) {
                        txt8Usuario.setText(resultadodeConsultar.getObject(1).toString());
                        txt9Contraseña.setText(resultadodeConsultar.getObject(2).toString());
                    }//find el while

                } catch (SQLException ex) {

                    Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {

                    Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }

                //contar el actualizado de maestros
                try {
                    contarAlumnos();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        } else {
            String mensaje = "";

            if (txt1IngresoMatricula.getText().length() <= 0) {
                mensaje = "-Matricula\n";
            }

            JOptionPane.showMessageDialog(rootPane, "INGRESE EL SIGUIENTE CAMPO:\n" + mensaje + "", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_buscar
    
    //[5] limpia los campos de la interfaz
    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        limpiarCampos();
        txt1IngresoMatricula.setText("");
        boton1Buscar.setEnabled(true);
        boton2Eliminar.setEnabled(false);

    }//GEN-LAST:event_cancelar

    //[1] cuenta el total de alumnos en la base de datos
    public void contarAlumnos() throws ClassNotFoundException, SQLException {
        ControlAlumno alumno = new ControlAlumno();
        totaldeAlumnos = alumno.contarTotalAlumnos();
        lab1TotaldeAlumnos.setText("Total de alumnos registrados: #" + (totaldeAlumnos));
    }

    //[2] limpia todos los campos de la interfaz
    public void limpiarCampos() {
        txt2Matricula.setText("");
        txt3NombreAlumno.setText("");
        txt4ApellidoPaterno.setText("");
        txt5ApellidoMaterno.setText("");
        txt6Grado.setText("");
        txt7Grupo.setText("");
        txt8Usuario.setText("");
        txt9Contraseña.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazEliminarAlumno().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(InterfazEliminarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1Buscar;
    private javax.swing.JButton boton2Eliminar;
    private javax.swing.JButton boton3Salir;
    private javax.swing.JButton boton4Cancelar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jp1EliminarAlumno;
    private javax.swing.JPanel jp2Matricula;
    private javax.swing.JPanel jp3DatosAlumno;
    private javax.swing.JPanel jp4DatosGrupo;
    private javax.swing.JPanel jp5DatosUsuario;
    private javax.swing.JLabel lab10Contraseña;
    private javax.swing.JLabel lab1TotaldeAlumnos;
    private javax.swing.JLabel lab2IngresoMatricula;
    private javax.swing.JLabel lab3Matricula;
    private javax.swing.JLabel lab4NombreAlumno;
    private javax.swing.JLabel lab5ApellidoPaterno;
    private javax.swing.JLabel lab6ApellidoMaterno;
    private javax.swing.JLabel lab7Grado;
    private javax.swing.JLabel lab8Grupo;
    private javax.swing.JLabel lab9Usuario;
    private javax.swing.JMenuBar menu1;
    private javax.swing.JTextField txt1IngresoMatricula;
    private javax.swing.JTextField txt2Matricula;
    private javax.swing.JTextField txt3NombreAlumno;
    private javax.swing.JTextField txt4ApellidoPaterno;
    private javax.swing.JTextField txt5ApellidoMaterno;
    private javax.swing.JTextField txt6Grado;
    private javax.swing.JTextField txt7Grupo;
    private javax.swing.JTextField txt8Usuario;
    private javax.swing.JTextField txt9Contraseña;
    // End of variables declaration//GEN-END:variables
}
