/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteMantenimientoUsuarios;

import com.inet.jortho.FileUserDictionary;
import com.inet.jortho.SpellChecker;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazModificarAlumno extends javax.swing.JFrame {

    String totaldeAlumnos;

    /**
     * Creates new form InterfazModificarAlumno
     */
    public InterfazModificarAlumno() throws ClassNotFoundException, SQLException {
        initComponents();

        //verifica la ortografia
        SpellChecker.setUserDictionaryProvider(new FileUserDictionary());
        SpellChecker.registerDictionaries(null, null);
        SpellChecker.register(txt3NombreAlumno);
        SpellChecker.register(txt4ApellidoPaterno);
        SpellChecker.register(txt5ApellidoMaterno);

        //establece la posicion central de la interfaz
        this.setLocationRelativeTo(null);

        //coloca el icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        //cuenta el total de alumnos
        contarAlumnos();

        //asigna el nombre de administrador a la interfaz
        jMenu2.setText("Mi cuenta: ADMINISTRADOR");

        //desactiva el boton guardar
        boton2Guardar.setEnabled(false);

        //des activa la opcion maximizar 
        this.setResizable(false);
        //desactiva la opcion cerrar
        setDefaultCloseOperation(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1ModificarAlumno = new javax.swing.JPanel();
        lab1TotaldeAlumnos = new javax.swing.JLabel();
        jp5Matricula = new javax.swing.JPanel();
        lab2Matricula = new javax.swing.JLabel();
        txt1IngresoMatricula = new javax.swing.JTextField();
        jp2DatosMaestro = new javax.swing.JPanel();
        lab4Nombre = new javax.swing.JLabel();
        lab5ApellidoPaterno = new javax.swing.JLabel();
        txt3NombreAlumno = new javax.swing.JTextField();
        txt4ApellidoPaterno = new javax.swing.JTextField();
        txt5ApellidoMaterno = new javax.swing.JTextField();
        lab6AplellidoMaterno = new javax.swing.JLabel();
        jp3Grupo = new javax.swing.JPanel();
        lab7Grado = new javax.swing.JLabel();
        lab8Grupo = new javax.swing.JLabel();
        cbox1Grado = new javax.swing.JComboBox();
        cbox2Grupo = new javax.swing.JComboBox();
        jp4Usuario = new javax.swing.JPanel();
        txt6Usuario = new javax.swing.JTextField();
        txt2Contraseña = new javax.swing.JTextField();
        lab3Contraseña = new javax.swing.JLabel();
        lab9Usuario = new javax.swing.JLabel();
        boton1Buscar = new javax.swing.JButton();
        boton2Guardar = new javax.swing.JButton();
        boton4Salir = new javax.swing.JButton();
        boton3Cancelar = new javax.swing.JButton();
        menu1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento Usuario/Modificar Usuario/Modificar Alumno");
        setMinimumSize(new java.awt.Dimension(596, 534));
        setResizable(false);

        jp1ModificarAlumno.setBackground(new java.awt.Color(245, 245, 239));
        jp1ModificarAlumno.setToolTipText("");

        lab1TotaldeAlumnos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab1TotaldeAlumnos.setText("Total de alumnos registrados:");

        jp5Matricula.setBackground(new java.awt.Color(253, 251, 251));
        jp5Matricula.setBorder(javax.swing.BorderFactory.createTitledBorder("Matricula"));

        lab2Matricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab2Matricula.setText("Ingrese la matricula:");

        txt1IngresoMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jp5MatriculaLayout = new javax.swing.GroupLayout(jp5Matricula);
        jp5Matricula.setLayout(jp5MatriculaLayout);
        jp5MatriculaLayout.setHorizontalGroup(
            jp5MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5MatriculaLayout.createSequentialGroup()
                .addComponent(lab2Matricula)
                .addGap(26, 26, 26)
                .addComponent(txt1IngresoMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );
        jp5MatriculaLayout.setVerticalGroup(
            jp5MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5MatriculaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp5MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1IngresoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jp2DatosMaestro.setBackground(new java.awt.Color(253, 251, 251));
        jp2DatosMaestro.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del alumno"));

        lab4Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab4Nombre.setText("Nombre del alumno:");

        lab5ApellidoPaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab5ApellidoPaterno.setText("Apellido paterno:");

        lab6AplellidoMaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab6AplellidoMaterno.setText("Apellido materno:");

        javax.swing.GroupLayout jp2DatosMaestroLayout = new javax.swing.GroupLayout(jp2DatosMaestro);
        jp2DatosMaestro.setLayout(jp2DatosMaestroLayout);
        jp2DatosMaestroLayout.setHorizontalGroup(
            jp2DatosMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2DatosMaestroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jp2DatosMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jp2DatosMaestroLayout.createSequentialGroup()
                        .addComponent(lab6AplellidoMaterno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt5ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2DatosMaestroLayout.createSequentialGroup()
                        .addGroup(jp2DatosMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab5ApellidoPaterno)
                            .addComponent(lab4Nombre))
                        .addGap(10, 10, 10)
                        .addGroup(jp2DatosMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt3NombreAlumno)
                            .addComponent(txt4ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp2DatosMaestroLayout.setVerticalGroup(
            jp2DatosMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2DatosMaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp2DatosMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2DatosMaestroLayout.createSequentialGroup()
                        .addComponent(txt3NombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2DatosMaestroLayout.createSequentialGroup()
                        .addComponent(lab4Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab5ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp2DatosMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab6AplellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jp3Grupo.setBackground(new java.awt.Color(253, 251, 251));
        jp3Grupo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del grupo"));

        lab7Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab7Grado.setText("Grado Asignado:");

        lab8Grupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab8Grupo.setText("Grupo Asignado:");

        cbox1Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox1Grado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));
        cbox1Grado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                obtenerGrados(evt);
            }
        });
        cbox1Grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerGrupos(evt);
            }
        });

        cbox2Grupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbox2Grupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));

        javax.swing.GroupLayout jp3GrupoLayout = new javax.swing.GroupLayout(jp3Grupo);
        jp3Grupo.setLayout(jp3GrupoLayout);
        jp3GrupoLayout.setHorizontalGroup(
            jp3GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3GrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp3GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab7Grado)
                    .addComponent(lab8Grupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp3GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbox1Grado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbox2Grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        jp3GrupoLayout.setVerticalGroup(
            jp3GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3GrupoLayout.createSequentialGroup()
                .addGroup(jp3GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3GrupoLayout.createSequentialGroup()
                        .addComponent(lab7Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab8Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbox1Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp3GrupoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(cbox2Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jp4Usuario.setBackground(new java.awt.Color(253, 251, 251));
        jp4Usuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        lab3Contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab3Contraseña.setText("Contraseña:");

        lab9Usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab9Usuario.setText("Usuario:");

        javax.swing.GroupLayout jp4UsuarioLayout = new javax.swing.GroupLayout(jp4Usuario);
        jp4Usuario.setLayout(jp4UsuarioLayout);
        jp4UsuarioLayout.setHorizontalGroup(
            jp4UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp4UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4UsuarioLayout.createSequentialGroup()
                        .addComponent(lab9Usuario)
                        .addGap(93, 93, 93)
                        .addComponent(txt6Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp4UsuarioLayout.createSequentialGroup()
                        .addComponent(lab3Contraseña)
                        .addGap(68, 68, 68)
                        .addComponent(txt2Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp4UsuarioLayout.setVerticalGroup(
            jp4UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4UsuarioLayout.createSequentialGroup()
                .addGroup(jp4UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab9Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp4UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab3Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        boton1Buscar.setBackground(new java.awt.Color(255, 255, 51));
        boton1Buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton1Buscar.setText("Buscar");
        boton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        boton2Guardar.setBackground(new java.awt.Color(51, 204, 0));
        boton2Guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2Guardar.setText("Guardar");
        boton2Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });

        boton4Salir.setBackground(new java.awt.Color(255, 255, 255));
        boton4Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton4Salir.setText("Salir");
        boton4Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        boton3Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        boton3Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton3Cancelar.setText("Cancelar");
        boton3Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        javax.swing.GroupLayout jp1ModificarAlumnoLayout = new javax.swing.GroupLayout(jp1ModificarAlumno);
        jp1ModificarAlumno.setLayout(jp1ModificarAlumnoLayout);
        jp1ModificarAlumnoLayout.setHorizontalGroup(
            jp1ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1ModificarAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab1TotaldeAlumnos)
                    .addGroup(jp1ModificarAlumnoLayout.createSequentialGroup()
                        .addGroup(jp1ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp1ModificarAlumnoLayout.createSequentialGroup()
                                .addGroup(jp1ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp1ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(boton2Guardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(boton1Buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(boton3Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1ModificarAlumnoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(boton4Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jp1ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp4Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp3Grupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp5Matricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp2DatosMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(58, 58, 58))
        );
        jp1ModificarAlumnoLayout.setVerticalGroup(
            jp1ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1ModificarAlumnoLayout.createSequentialGroup()
                .addComponent(lab1TotaldeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jp1ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1ModificarAlumnoLayout.createSequentialGroup()
                        .addComponent(jp5Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jp2DatosMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1ModificarAlumnoLayout.createSequentialGroup()
                        .addComponent(boton1Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton2Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton3Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton4Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp3Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp4Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu2.setText("Mi cuenta");
        jMenu2.setToolTipText("");
        menu1.add(jMenu2);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1ModificarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1ModificarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //[3] busca al alumno segun la matricula indicada
    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        //limpiar todos los campos
        limpiarCampos();

        //variables para poder saber si todo esta correcto
        boolean numeroEmpleadoCorrecto = false;
        if (txt1IngresoMatricula.getText().length() != 0) {

            //identificar si la matricula  es correcta
            try {
                if (Integer.parseInt(txt1IngresoMatricula.getText()) > 0) {
                    numeroEmpleadoCorrecto = true;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "MATRICULA INCORRECTA", "ERROR", JOptionPane.ERROR_MESSAGE);
                boton1Buscar.setEnabled(true);
                boton2Guardar.setEnabled(false);
            }

            if (numeroEmpleadoCorrecto == true) {
                boton1Buscar.setEnabled(false);
                boton2Guardar.setEnabled(true);
                ControlAlumno alumnoC = new ControlAlumno();
                ControlGrupo grupoC = new ControlGrupo();
                ControlUsuario usuarioC = new ControlUsuario();
                try {

                    //obtener alumno
                    ResultSet resultadodeConsultar = alumnoC.consultar(txt1IngresoMatricula.getText());

                    while (resultadodeConsultar.next()) {

                        txt3NombreAlumno.setText(resultadodeConsultar.getObject(2).toString());
                        txt4ApellidoPaterno.setText(resultadodeConsultar.getObject(3).toString());
                        txt5ApellidoMaterno.setText(resultadodeConsultar.getObject(4).toString());

                    }//find el while

                    //cuando no se ha encontrado al alumno
                    if (txt3NombreAlumno.getText().length() <= 0
                            && txt4ApellidoPaterno.getText().length() <= 0
                            && txt5ApellidoMaterno.getText().length() <= 0) {
                        JOptionPane.showMessageDialog(rootPane, "MATRICULA NO SE ENCUENTRA", "ERROR", JOptionPane.ERROR_MESSAGE);
                        txt1IngresoMatricula.setEnabled(true);
                        boton1Buscar.setEnabled(true);
                        boton2Guardar.setEnabled(false);
                    } else {
                        //bloquear modificar matricula
                        txt1IngresoMatricula.setEnabled(false);
                    }

                    //obtener informacion del Grupo
                    resultadodeConsultar = grupoC.consultarGrupodeAlumno(txt1IngresoMatricula.getText());
                    while (resultadodeConsultar.next()) {
                        switch (Integer.parseInt(resultadodeConsultar.getObject(1).toString())) {
                            case 3:
                                cbox1Grado.setSelectedIndex(1);
                                break;
                            case 4:
                                cbox1Grado.setSelectedIndex(2);
                                break;
                            case 5:
                                cbox1Grado.setSelectedIndex(3);
                                break;
                            case 6:
                                cbox1Grado.setSelectedIndex(4);
                                break;
                        }

                        switch (resultadodeConsultar.getObject(2).toString().charAt(0)) {
                            case 'A':
                                cbox2Grupo.setSelectedIndex(1);
                                break;
                            case 'B':
                                cbox2Grupo.setSelectedIndex(2);
                                break;
                            case 'C':
                                cbox2Grupo.setSelectedIndex(3);
                                break;
                        }

                    }//find el while

                    //obtener informacion del usuario
                    resultadodeConsultar = usuarioC.consultar(txt1IngresoMatricula.getText(), "alumno");
                    while (resultadodeConsultar.next()) {
                        txt6Usuario.setText(resultadodeConsultar.getObject(1).toString());
                        txt2Contraseña.setText(resultadodeConsultar.getObject(2).toString());
                    }//find el while

                } catch (SQLException ex) {

                    Logger.getLogger(InterfazModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {

                    Logger.getLogger(InterfazModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }

                //contar el actualizado de maestros
                try {
                    contarAlumnos();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(InterfazModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(InterfazModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        } else {
            String mensaje = "";

            if (txt1IngresoMatricula.getText().length() <= 0) {
                mensaje = "-Numero de empleado\n";
            }

            JOptionPane.showMessageDialog(rootPane, "INGRESE EL SIGUIENTE CAMPO:\n" + mensaje + "", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_buscar

    //[4] verifica los campos a modificar
    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        // TODO add your handling code here:
        //variables para poder saber si todo esta correcto
        boolean numeroEmpleadoCorrecto = false, nombre = false, apellidoPaterno = false, apellidoMaterno = false, usuario = false, contraseña = false;
        boolean numeroEmpleadoExiste = false;
        //comparando si lo que se ha ingresado tiene una longitud distinta de 0
        if (txt1IngresoMatricula.getText().length() != 0
                && txt3NombreAlumno.getText().length() != 0
                && txt4ApellidoPaterno.getText().length() != 0
                && txt5ApellidoMaterno.getText().length() != 0
                && txt6Usuario.getText().length() != 0
                && txt2Contraseña.getText().length() != 0
                && cbox1Grado.getSelectedIndex() != 0
                && cbox2Grupo.getSelectedIndex() != 0) {

            //identificar si el numero del maestro es correcto
            try {
                if (Integer.parseInt(txt1IngresoMatricula.getText()) > 0) {
                    numeroEmpleadoCorrecto = true;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "EL NUMERO DE MAESTRO ES INCORRECTO", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            //identificar si los datos del maestro son correcto
            nombre = esCadena(txt3NombreAlumno.getText(), "EL NOMBRE DEL MAESTRO ES INCORRECTO");
            apellidoPaterno = esCadena(txt4ApellidoPaterno.getText(), "EL APELLIDO PATERNO DEL MAESTRO ES INCORRECTO");
            apellidoMaterno = esCadena(txt5ApellidoMaterno.getText(), "EL APELLIDO MATERNO DEL MAESTRO ES INCORRECTO");
            usuario = esCadena(txt6Usuario.getText(), "EL USUARIO ES INCORRECTO: SOLO PUEDE CONTENER LETRAS");
            usuario = esMayor(txt6Usuario.getText());
            if (usuario == false) {
                JOptionPane.showMessageDialog(rootPane, "USUARIO MUY CORTO: MINIMO 5 CARACTERES", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            contraseña = esMayor(txt2Contraseña.getText());
            if (contraseña == false) {
                JOptionPane.showMessageDialog(rootPane, "CONTRASEÑA MUY CORTA: MINIMO 5 CARACTERES", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            //revisa si el texto ingresado contiene exclusivamente letras
            if (esTextoPuro(txt3NombreAlumno.getText())
                    && esTextoPuro(txt4ApellidoPaterno.getText())
                    && esTextoPuro(txt5ApellidoMaterno.getText())) {

                //todos los datos estan correctos
                if (numeroEmpleadoCorrecto == true && nombre == true && apellidoPaterno == true && apellidoMaterno == true && usuario == true && contraseña == true) {
                    int correcto = JOptionPane.showConfirmDialog(rootPane, "TODO ESTA CORRECTO?", "FELICIDADES", JOptionPane.YES_NO_OPTION);

                    //envia a control maestro para el registro
                    if (correcto == 0) {

                        modificar();
                        txt1IngresoMatricula.setEnabled(true);
                        boton1Buscar.setEnabled(true);
                        boton2Guardar.setEnabled(false);
                    }

                }

            } else {
                String mensaje = "";
                mensaje = datosACorregir();
                JOptionPane.showMessageDialog(rootPane, "REVISAR LOS SIGUIENTES CAMPOS:\n" + mensaje + "", "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } else {

            String mensaje = datosPorIngresar();

            JOptionPane.showMessageDialog(rootPane, "INGRESE LOS SIGUIENTES CAMPOS:\n" + mensaje + "", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_guardar

    //[12] cierra la interfaz
    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        // TODO add your handling code here:
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {
            limpiarCampos();
            txt1IngresoMatricula.setEnabled(true);
            txt1IngresoMatricula.setText("");
            boton1Buscar.setEnabled(true);
            boton2Guardar.setEnabled(false);
            this.setVisible(false);

        }
    }//GEN-LAST:event_salir

    //[11] cancela y limpia todos los campos
    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        txt1IngresoMatricula.setEnabled(true);
        limpiarCampos();
        txt1IngresoMatricula.setText("");
        boton1Buscar.setEnabled(true);
        boton2Guardar.setEnabled(false);

    }//GEN-LAST:event_cancelar

    private void obtenerGrados(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_obtenerGrados
        // TODO add your handling code here:

        limpiarCampos();
        ControlGrupo Cgrupo = new ControlGrupo();
        try {
            ResultSet obtenerGrados = Cgrupo.obtenerGrupos();

            String grado = "";

            while (obtenerGrados.next()) {
                grado = obtenerGrados.getObject(1).toString();
                int totalGrado = cbox1Grado.getItemCount();
                int maximo = 0;

                for (int i = 0; i < totalGrado; i++) {
                    if (grado.compareTo(cbox1Grado.getItemAt(i).toString()) == 0) {
                        maximo++;

                    }
                }
                if (maximo == 0) {
                    this.cbox1Grado.addItem(grado);
                }

            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error al intentar obtener datos a la bd");
        }
    }//GEN-LAST:event_obtenerGrados

    private void obtenerGrupos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerGrupos
        cbox2Grupo.removeAllItems();
        cbox2Grupo.addItem("Seleccione una opción");
        ControlGrupo Cgrupo = new ControlGrupo();
        try {
            ResultSet obtenerGrupos = Cgrupo.obtenerGrupos(Integer.parseInt(cbox1Grado.getSelectedItem().toString()));
            System.out.println("seleccione: " + cbox1Grado.getSelectedItem().toString());
            String grupo = "";

            while (obtenerGrupos.next()) {
                grupo = obtenerGrupos.getObject(1).toString();
                this.cbox2Grupo.addItem(grupo);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error al intentar obtener datos a la bd");
        } catch (NumberFormatException | NullPointerException ex) {
        }
    }//GEN-LAST:event_obtenerGrupos

    //[7] asigna los nuevos valores ingresados
    public void modificar() {
        ControlAlumno alumnoC = new ControlAlumno();
        ControlGrupo grupoC = new ControlGrupo();
        ControlUsuario usuarioC = new ControlUsuario();
        try {

            //registro de maestro
            alumnoC.modificar(txt1IngresoMatricula.getText(), txt3NombreAlumno.getText(), txt4ApellidoPaterno.getText(), txt5ApellidoMaterno.getText());
            //registro de grupo
            grupoC.modificarGrupoAlumno(cbox1Grado.getSelectedIndex(), cbox2Grupo.getSelectedIndex(), txt1IngresoMatricula.getText());
            //registro de usuario
            usuarioC.modificarUsuarioAlumno(txt1IngresoMatricula.getText(), txt6Usuario.getText(), txt2Contraseña.getText());
            JOptionPane.showMessageDialog(rootPane, "MODIFICACION EXITOSA", "FELICIDADES", JOptionPane.WARNING_MESSAGE);

        } catch (SQLException ex) {
            Logger.getLogger(InterfazModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InterfazModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        //limpia los campos
        limpiarCampos();
        try {
            contarAlumnos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InterfazModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(InterfazModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //[2] limpia los campos de la interfaz
    public void limpiarCampos() {
        txt3NombreAlumno.setText("");
        txt4ApellidoPaterno.setText("");
        txt5ApellidoMaterno.setText("");

        txt6Usuario.setText("");
        txt2Contraseña.setText("");

        cbox2Grupo.removeAllItems();
        cbox2Grupo.addItem("Seleccione una opción");

        cbox1Grado.removeAllItems();
        cbox1Grado.addItem("Seleccione una opción");

    }

    //[10] indica que datos faltan por ingresar
    public String datosPorIngresar() {
        String mensaje = "";

        if (txt1IngresoMatricula.getText().length() <= 0) {
            mensaje = "-Matricula\n";
        }
        if (txt3NombreAlumno.getText().length() <= 0) {
            mensaje = mensaje + "-Nombre del alumno\n";
        }
        if (txt4ApellidoPaterno.getText().length() <= 0) {
            mensaje = mensaje + "-Apellido Paterno\n";
        }
        if (txt5ApellidoMaterno.getText().length() <= 0) {
            mensaje = mensaje + "-Apellido Materno\n";
        }
        if (cbox1Grado.getSelectedIndex() <= 0) {
            mensaje = mensaje + "-Grado\n";
        }
        if (cbox2Grupo.getSelectedIndex() <= 0) {
            mensaje = mensaje + "-Grupo\n";
        }
        if (txt6Usuario.getText().length() <= 0) {
            mensaje = mensaje + "-Usuario\n";
        }
        if (txt2Contraseña.getText().length() <= 0) {
            mensaje = mensaje + "-Contraseña\n";
        }
        return mensaje;
    }

    //[8]indica que datos faltan por corregir
    public String datosACorregir() {
        String mensaje = "";

        if (!esTextoPuro(txt3NombreAlumno.getText())) {
            mensaje = mensaje + "-Nombre del alumno\n";
        }
        if (!esTextoPuro(txt4ApellidoPaterno.getText())) {
            mensaje = mensaje + "-Apellido Paterno\n";
        }
        if (!esTextoPuro(txt5ApellidoMaterno.getText())) {
            mensaje = mensaje + "-Apellido Materno\n";
        }
        if (!esTextoPuro(txt6Usuario.getText())) {
            mensaje = mensaje + "-Usuario\n";
        }
        if (!esTextoPuro(txt2Contraseña.getText())) {
            mensaje = mensaje + "-Contraseña\n";
        }

        return mensaje;
    }

    //[9]verifica que el texto ingresado contenga solo letras
    public boolean esTextoPuro(String texto) {
        boolean resultado = false;

        for (int i = 0; i < texto.length(); i++) {
            if (((int) texto.charAt(i) >= 65 && (int) texto.charAt(i) <= 90) || ((int) texto.charAt(i) >= 97 && (int) texto.charAt(i) <= 122)) {
                resultado = true;
            } else {
                return false;
            }

        }

        return resultado;
    }

    //[1]cuenta el total de alumnos registrados en la base de datos
    public void contarAlumnos() throws ClassNotFoundException, SQLException {
        ControlAlumno alumno = new ControlAlumno();
        totaldeAlumnos = alumno.contarTotalAlumnos();
        lab1TotaldeAlumnos.setText("Total de alumnos registrados: #" + (totaldeAlumnos));
    }

    //[5] verifica que el texto ingresado no contenga numeros
    public boolean esCadena(String texto, String mensaje) {
        //identificar si el nombre del maestro es correcto
        boolean resultado = false;
        int contadordeNumeros = 0;
        String numerosAcomparar[] = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "0"};

        for (int j = 0; j < numerosAcomparar.length; j++) {
            if (texto.contains(numerosAcomparar[j])) {
                contadordeNumeros++;
            }
        }
        if (contadordeNumeros != 0) {
            JOptionPane.showMessageDialog(rootPane, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            resultado = true;
        }

        return resultado;
    }

    //[6]verificq que la cadena sea mayor e igual a 5 caracteres  
    public boolean esMayor(String texto) {
        boolean resultado = false;

        if (texto.length() >= 5) {
            resultado = true;
        }
        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazModificarAlumno().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(InterfazModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1Buscar;
    private javax.swing.JButton boton2Guardar;
    private javax.swing.JButton boton3Cancelar;
    private javax.swing.JButton boton4Salir;
    private javax.swing.JComboBox cbox1Grado;
    private javax.swing.JComboBox cbox2Grupo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jp1ModificarAlumno;
    private javax.swing.JPanel jp2DatosMaestro;
    private javax.swing.JPanel jp3Grupo;
    private javax.swing.JPanel jp4Usuario;
    private javax.swing.JPanel jp5Matricula;
    private javax.swing.JLabel lab1TotaldeAlumnos;
    private javax.swing.JLabel lab2Matricula;
    private javax.swing.JLabel lab3Contraseña;
    private javax.swing.JLabel lab4Nombre;
    private javax.swing.JLabel lab5ApellidoPaterno;
    private javax.swing.JLabel lab6AplellidoMaterno;
    private javax.swing.JLabel lab7Grado;
    private javax.swing.JLabel lab8Grupo;
    private javax.swing.JLabel lab9Usuario;
    private javax.swing.JMenuBar menu1;
    private javax.swing.JTextField txt1IngresoMatricula;
    private javax.swing.JTextField txt2Contraseña;
    private javax.swing.JTextField txt3NombreAlumno;
    private javax.swing.JTextField txt4ApellidoPaterno;
    private javax.swing.JTextField txt5ApellidoMaterno;
    private javax.swing.JTextField txt6Usuario;
    // End of variables declaration//GEN-END:variables
}
