/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteMantenimientoUsuarios;

import PaqueteLogin.InterfazLogin;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazConsultaGeneralMaestro extends javax.swing.JFrame {

    /**
     * Creates new form InterfazConsultaGeneralMaestro
     */
    public InterfazConsultaGeneralMaestro() {
        initComponents();
        //establece la posicion central la interfaz
        this.setLocationRelativeTo(null);

        //coloca el icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        //des activa el maximizar y el cerrar
        this.setResizable(false);
        setDefaultCloseOperation(0);

        //asigna el nombre de administrador en la interfaz
        jMenu1.setText("Mi cuenta: ADMINISTRADOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1ConsultaMaestro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1Maestro = new javax.swing.JTable();
        boton1Buscar = new javax.swing.JButton();
        boton2Salir = new javax.swing.JButton();
        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MantenimientoUsuario/ConsultaGeneralMaestro");
        setMinimumSize(new java.awt.Dimension(1162, 479));
        setResizable(false);

        jp1ConsultaMaestro.setBackground(new java.awt.Color(253, 251, 251));
        jp1ConsultaMaestro.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de los maestros"));

        table1Maestro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de lista", "Número de empleado", "Nombre del maestro", "Apellido paterno", "Apellido materno", "Grado asignado", "Grupo asignado", "Usuario", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1Maestro);
        if (table1Maestro.getColumnModel().getColumnCount() > 0) {
            table1Maestro.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        boton1Buscar.setBackground(new java.awt.Color(204, 255, 51));
        boton1Buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton1Buscar.setText("Buscar");
        boton1Buscar.setToolTipText("");
        boton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        boton2Salir.setBackground(new java.awt.Color(255, 255, 255));
        boton2Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2Salir.setText("Salir");
        boton2Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        javax.swing.GroupLayout jp1ConsultaMaestroLayout = new javax.swing.GroupLayout(jp1ConsultaMaestro);
        jp1ConsultaMaestro.setLayout(jp1ConsultaMaestroLayout);
        jp1ConsultaMaestroLayout.setHorizontalGroup(
            jp1ConsultaMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1ConsultaMaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1ConsultaMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton2Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton1Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE))
        );
        jp1ConsultaMaestroLayout.setVerticalGroup(
            jp1ConsultaMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1ConsultaMaestroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jp1ConsultaMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp1ConsultaMaestroLayout.createSequentialGroup()
                        .addComponent(boton1Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton2Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu1.setText("Mi cuenta");
        jMenu1.setToolTipText("");
        menu1.add(jMenu1);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1ConsultaMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jp1ConsultaMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //[3] cierra la interfaz
    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        // TODO add your handling code here:
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {

            try {
                DefaultTableModel modelo = (DefaultTableModel) table1Maestro.getModel();
                int total = table1Maestro.getRowCount();
                for (int i = 0; i < total; i++) {
                    modelo.removeRow(0);
                }
            } catch (NumberFormatException e) {
                System.out.println(e.toString());
            }
            this.setVisible(false);

        }
    }//GEN-LAST:event_salir

    //[1] metodo que obtiene toda la informacion de los maestros
    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        // TODO add your handling code here:

        try {
            DefaultTableModel modelo = (DefaultTableModel) table1Maestro.getModel();
            int total = table1Maestro.getRowCount();
            for (int i = 0; i < total; i++) {
                modelo.removeRow(0);
            }
        } catch (NumberFormatException e) {
            System.out.println(e.toString());
        }

        ControlMaestro maestroC = new ControlMaestro();

        try {
            ResultSet conjuntoResultados = maestroC.consultarMaestroGrupoUsuario();
            llenarTabla(conjuntoResultados);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InterfazConsultaGeneralMaestro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buscar

    //[2] llena la tabla con la informacion obtenida
    public void llenarTabla(ResultSet conjuntoResultados) throws ClassNotFoundException, SQLException {

        int posicion = 0;

        DefaultTableModel modelo = (DefaultTableModel) table1Maestro.getModel();

        while (conjuntoResultados.next()) {
            modelo.addRow(new Object[]{
                (posicion + 1),
                conjuntoResultados.getObject(1).toString(),
                conjuntoResultados.getObject(2).toString(),
                conjuntoResultados.getObject(3).toString(),
                conjuntoResultados.getObject(4).toString(),
                conjuntoResultados.getObject(5).toString(),
                conjuntoResultados.getObject(6).toString(),
                conjuntoResultados.getObject(7).toString(),
                conjuntoResultados.getObject(8).toString(),});
            posicion++;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaGeneralMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaGeneralMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaGeneralMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaGeneralMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConsultaGeneralMaestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1Buscar;
    private javax.swing.JButton boton2Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp1ConsultaMaestro;
    private javax.swing.JMenuBar menu1;
    private javax.swing.JTable table1Maestro;
    // End of variables declaration//GEN-END:variables

}
