package PaqueteCalificaciones;

import PaqueteLogin.InterfazLogin;
import PaqueteMantenimientodeMaterias.ControlMateria;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazConsultarCalificaciones extends javax.swing.JFrame {

    boolean materiaSeleccionada = false;
    boolean gradoSeleccionado = false;
    boolean grupoSeleccionado = false;
    int totaldeAlumnos = 0;
    public int idUsuario;
    public String nombreUsuario;

    /**
     * Creates new form InterfazConsultarCalificacioness
     */
    public InterfazConsultarCalificaciones() {
        initComponents();

        //establece la interfaz de manera central
        this.setLocationRelativeTo(null);

        //colocar icono a la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        //des activa la opcion maximizar 
        this.setResizable(false);
        //desactiva la opcion cerrar
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1ConsultarCalificaciones = new javax.swing.JPanel();
        jp2InformaciondeEvaluacion = new javax.swing.JPanel();
        lab2Grado = new javax.swing.JLabel();
        lab4Evaluacion = new javax.swing.JLabel();
        cbox2Grado = new javax.swing.JComboBox();
        cbox3Evaluacion = new javax.swing.JComboBox();
        lab1Materia = new javax.swing.JLabel();
        cbox1Materia = new javax.swing.JComboBox();
        cbox4Grupo = new javax.swing.JComboBox();
        lab3Grupo = new javax.swing.JLabel();
        boton1Consultar = new javax.swing.JButton();
        boton2Salir = new javax.swing.JButton();
        jp3Resultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1Calificaciones = new javax.swing.JTable();
        boton3Cancelar = new javax.swing.JButton();
        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jitem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ConsultarCalificaciones");
        setMinimumSize(new java.awt.Dimension(878, 563));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                personalizarInterfaz(evt);
            }
        });

        jp1ConsultarCalificaciones.setBackground(new java.awt.Color(245, 245, 239));

        jp2InformaciondeEvaluacion.setBackground(new java.awt.Color(253, 251, 251));
        jp2InformaciondeEvaluacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de la evaluación "));

        lab2Grado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab2Grado.setText("Grado:");

        lab4Evaluacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab4Evaluacion.setText("Evaluación:");

        cbox2Grado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));
        cbox2Grado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                obtenerGrados(evt);
            }
        });
        cbox2Grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradoSeleccionado(evt);
            }
        });

        cbox3Evaluacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));

        lab1Materia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab1Materia.setText("Materia:");

        cbox1Materia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));
        cbox1Materia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                obtenerMaterias(evt);
            }
        });
        cbox1Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaSelecionada(evt);
            }
        });

        cbox4Grupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));
        cbox4Grupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                obtenerGrupos(evt);
            }
        });
        cbox4Grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoSeleccionado(evt);
            }
        });

        lab3Grupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab3Grupo.setText("Grupo:");

        javax.swing.GroupLayout jp2InformaciondeEvaluacionLayout = new javax.swing.GroupLayout(jp2InformaciondeEvaluacion);
        jp2InformaciondeEvaluacion.setLayout(jp2InformaciondeEvaluacionLayout);
        jp2InformaciondeEvaluacionLayout.setHorizontalGroup(
            jp2InformaciondeEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2InformaciondeEvaluacionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jp2InformaciondeEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab2Grado)
                    .addGroup(jp2InformaciondeEvaluacionLayout.createSequentialGroup()
                        .addComponent(lab4Evaluacion)
                        .addGap(23, 23, 23)
                        .addComponent(cbox3Evaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2InformaciondeEvaluacionLayout.createSequentialGroup()
                        .addGroup(jp2InformaciondeEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab1Materia)
                            .addComponent(lab3Grupo))
                        .addGap(42, 42, 42)
                        .addGroup(jp2InformaciondeEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbox2Grado, javax.swing.GroupLayout.Alignment.LEADING, 0, 153, Short.MAX_VALUE)
                            .addComponent(cbox1Materia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbox4Grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jp2InformaciondeEvaluacionLayout.setVerticalGroup(
            jp2InformaciondeEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2InformaciondeEvaluacionLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jp2InformaciondeEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox1Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp2InformaciondeEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox2Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp2InformaciondeEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab3Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox4Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp2InformaciondeEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab4Evaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox3Evaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        boton1Consultar.setBackground(new java.awt.Color(255, 255, 51));
        boton1Consultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton1Consultar.setText("Consultar");
        boton1Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar(evt);
            }
        });

        boton2Salir.setBackground(new java.awt.Color(255, 255, 255));
        boton2Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2Salir.setText("Salir");
        boton2Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        jp3Resultados.setBackground(new java.awt.Color(253, 251, 251));
        jp3Resultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        table1Calificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de lista", "Matricula", "Nombre del alumno", "Apellido paterno", "Apellido materno", "Calificación"
            }
        ));
        jScrollPane1.setViewportView(table1Calificaciones);

        javax.swing.GroupLayout jp3ResultadosLayout = new javax.swing.GroupLayout(jp3Resultados);
        jp3Resultados.setLayout(jp3ResultadosLayout);
        jp3ResultadosLayout.setHorizontalGroup(
            jp3ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3ResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp3ResultadosLayout.setVerticalGroup(
            jp3ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3ResultadosLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        boton3Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        boton3Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton3Cancelar.setText("Cancelar");
        boton3Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        javax.swing.GroupLayout jp1ConsultarCalificacionesLayout = new javax.swing.GroupLayout(jp1ConsultarCalificaciones);
        jp1ConsultarCalificaciones.setLayout(jp1ConsultarCalificacionesLayout);
        jp1ConsultarCalificacionesLayout.setHorizontalGroup(
            jp1ConsultarCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1ConsultarCalificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1ConsultarCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1ConsultarCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(boton1Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(boton2Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(boton3Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp1ConsultarCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp3Resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp2InformaciondeEvaluacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jp1ConsultarCalificacionesLayout.setVerticalGroup(
            jp1ConsultarCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1ConsultarCalificacionesLayout.createSequentialGroup()
                .addGroup(jp1ConsultarCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1ConsultarCalificacionesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(boton1Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton3Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton2Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1ConsultarCalificacionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jp2InformaciondeEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp3Resultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu1.setText("Mi cuenta");
        jMenu1.setToolTipText("");

        jitem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar sesion.png"))); // NOI18N
        jitem1.setText("Cerrar sesión  ");
        jitem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesion(evt);
            }
        });
        jMenu1.add(jitem1);

        menu1.add(jMenu1);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1ConsultarCalificaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp1ConsultarCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //[12]cierra la interfaz
    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        // TODO add your handling code here:
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {
            vaciarTabla();
            cbox1Materia.setSelectedIndex(0);
            cbox2Grado.setSelectedIndex(0);
            cbox4Grupo.setSelectedIndex(0);
            cbox3Evaluacion.removeAllItems();
            cbox3Evaluacion.addItem("Seleccione una opción");
            this.setVisible(false);

        }
    }//GEN-LAST:event_salir

    //[5] busca la evaluacion que coincide con la materia, grado y grupo seleccionado
    public void buscarEvaluacion() {
        if (materiaSeleccionada && gradoSeleccionado && grupoSeleccionado) {

            cbox3Evaluacion.removeAllItems();
            cbox3Evaluacion.addItem("Seleccione una opción");
            ControlEvaluacion evaluacion = new ControlEvaluacion();
            try {

                ResultSet consultarIdMateriadeEvaluacion = evaluacion.consultarIdMateriadeEvaluacion(cbox1Materia.getSelectedItem().toString());
                int idMateria = 0;
                while (consultarIdMateriadeEvaluacion.next()) {
                    idMateria = Integer.parseInt(consultarIdMateriadeEvaluacion.getObject(1).toString());
                }

                ResultSet resultados = evaluacion.consultarNombre(idMateria, cbox4Grupo.getSelectedItem().toString(), Integer.parseInt(cbox2Grado.getSelectedItem().toString()));
                mostrarEvaluaciones(resultados);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazConsultarCalificaciones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException | NullPointerException e) {
            }

        }

    }

    //[6] muestra los nombres de las evaluaciones que se encontraron en buscarEvaluacion
    public void mostrarEvaluaciones(ResultSet resultados) throws SQLException {

        while (resultados.next()) {
            cbox3Evaluacion.addItem(resultados.getObject(1));

        }

    }

    //[8] busca las calificaciones de los alumnos relacionadas con el nombre de la evaluacion seleccionada
    private void consultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar
        vaciarTabla();
        if (materiaSeleccionada && gradoSeleccionado && grupoSeleccionado) {
            vaciarTabla();
            ControlEvaluacion evaluacion = new ControlEvaluacion();
            try {
//                ResultSet resultado = evaluacion.consultarIdEvaluacion(cbox3Evaluacion.getSelectedItem().toString());
//                int idMateria = 0;
//                while (resultado.next()) {
//                    idMateria = Integer.parseInt(resultado.getObject(1).toString());
//                }

                ControlCalificaciones calificacion = new ControlCalificaciones();
                ResultSet resultadoCalificaciones = calificacion.consultar(cbox3Evaluacion.getSelectedItem().toString(), Integer.parseInt(cbox2Grado.getSelectedItem().toString()), cbox4Grupo.getSelectedItem().toString());
                llenarTabla(resultadoCalificaciones);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazConsultarCalificaciones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NullPointerException ex) {
                System.out.println("no hay evaluación que seleccionar");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "SELECCIONE \nMateria \nGrado \nGrupo \nEvaluacion", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_consultar

    //[11] permite salir completamente de la aplicacion 
    private void cerrarSesion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesion

        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {
            InterfazLogin login = new InterfazLogin();
            login.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesion

    //[1] asigna el numbre de usuario y su numero de empleado a la interfaz
    private void personalizarInterfaz(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_personalizarInterfaz

        jMenu1.setText("Mi cuenta: " + nombreUsuario + " : " + idUsuario);
    }//GEN-LAST:event_personalizarInterfaz

    //[10] limpia todos los campos de la interfaz
    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        vaciarTabla();
        cbox1Materia.setSelectedIndex(0);
        cbox2Grado.setSelectedIndex(0);
        cbox4Grupo.setSelectedIndex(0);
        cbox3Evaluacion.removeAllItems();
        cbox3Evaluacion.addItem("Seleccione una opción");
    }//GEN-LAST:event_cancelar

    //[2] indica si se ha seleccionada la materia
    private void materiaSelecionada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaSelecionada
        if (cbox1Materia.getSelectedIndex() != 0) {
            materiaSeleccionada = true;
            buscarEvaluacion();
            vaciarTabla();
        } else {
            materiaSeleccionada = false;
            vaciarTabla();
            cbox3Evaluacion.removeAllItems();
            cbox3Evaluacion.addItem("Seleccione una opción");
        }

    }//GEN-LAST:event_materiaSelecionada

    //[3] indica si se ha seleccionado el grado
    private void gradoSeleccionado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradoSeleccionado
        if (cbox2Grado.getSelectedIndex() != 0) {
            gradoSeleccionado = true;
            buscarEvaluacion();
            vaciarTabla();
        } else {
            gradoSeleccionado = false;
            vaciarTabla();
            cbox3Evaluacion.removeAllItems();
            cbox3Evaluacion.addItem("Seleccione una opción");
        }

    }//GEN-LAST:event_gradoSeleccionado

    //[4] indica si se ha seleccionado el grupo
    private void grupoSeleccionado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoSeleccionado
        if (cbox4Grupo.getSelectedIndex() != 0) {
            grupoSeleccionado = true;
            buscarEvaluacion();
            vaciarTabla();
        } else {
            grupoSeleccionado = false;
            vaciarTabla();
            cbox3Evaluacion.removeAllItems();
            cbox3Evaluacion.addItem("Seleccione una opción");
        }    }//GEN-LAST:event_grupoSeleccionado

    public void limpiarCampos() {

        cbox1Materia.removeAllItems();
        cbox1Materia.addItem("Seleccione una opción");

        cbox2Grado.removeAllItems();
        cbox2Grado.addItem("Seleccione una opción");
        vaciarTabla();

    }

    private void obtenerMaterias(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_obtenerMaterias
        // TODO add your handling code here:
        limpiarCampos();
        ControlMateria cMateria = new ControlMateria();
        try {
            ResultSet obtenerMaterias = cMateria.obtenerMaterias();

            while (obtenerMaterias.next()) {
                cbox1Materia.addItem(obtenerMaterias.getObject(1));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_obtenerMaterias

    private void obtenerGrados(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_obtenerGrados
        // TODO add your handling code here:

        PaqueteMantenimientoUsuarios.ControlGrupo Cgrupo = new PaqueteMantenimientoUsuarios.ControlGrupo();
        try {
            ResultSet obtenerGrados = Cgrupo.obtenerGrupos();

            String grado = "";

            while (obtenerGrados.next()) {
                grado = obtenerGrados.getObject(1).toString();
                int totalGrado = cbox2Grado.getItemCount();
                int maximo = 0;

                for (int i = 0; i < totalGrado; i++) {
                    if (grado.compareTo(cbox2Grado.getItemAt(i).toString()) == 0) {
                        maximo++;

                    }
                }
                if (maximo == 0) {
                    this.cbox2Grado.addItem(grado);
                }

            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error al intentar obtener datos a la bd");
        }
    }//GEN-LAST:event_obtenerGrados

    private void obtenerGrupos(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_obtenerGrupos
        // TODO add your handling code here:
        cbox4Grupo.removeAllItems();
        cbox4Grupo.addItem("Seleccione una opción");
        PaqueteMantenimientoUsuarios.ControlGrupo Cgrupo = new PaqueteMantenimientoUsuarios.ControlGrupo();
        try {
            ResultSet obtenerGrupos = Cgrupo.obtenerGrupos(Integer.parseInt(cbox2Grado.getSelectedItem().toString()));
            System.out.println("seleccione: " + cbox2Grado.getSelectedItem().toString());
            String grupo = "";

            while (obtenerGrupos.next()) {
                grupo = obtenerGrupos.getObject(1).toString();
                this.cbox4Grupo.addItem(grupo);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error al intentar obtener datos a la bd");
        } catch (NumberFormatException | NullPointerException ex) {
        }
    }//GEN-LAST:event_obtenerGrupos

    //[7] asigna espacios en blanco a cada una de las celdas de la tabla para borrar su contenido
    public void vaciarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) table1Calificaciones.getModel();
        int total = table1Calificaciones.getRowCount();
        for (int i = 0; i < total; i++) {
            modelo.removeRow(0);
        }

    }

    //[9] asigna a la tabla cada una de los datos de los alumnos que coinciden con la evaluacion seleccionada
    public void llenarTabla(ResultSet resultadoCalificaciones) throws SQLException {
        totaldeAlumnos = 0;

        int total = 0;
        while (resultadoCalificaciones.next()) {
            total++;
        }
        resultadoCalificaciones.beforeFirst();

        DefaultTableModel modelo = (DefaultTableModel) table1Calificaciones.getModel();
        while (resultadoCalificaciones.next()) {
            modelo.addRow(new Object[]{
                (totaldeAlumnos + 1),
                resultadoCalificaciones.getObject(1).toString(),
                resultadoCalificaciones.getObject(2).toString(),
                resultadoCalificaciones.getObject(3).toString(),
                resultadoCalificaciones.getObject(4).toString(),
                resultadoCalificaciones.getObject(5).toString()
            });

            totaldeAlumnos++;

        }
        if (total == 0) {
            JOptionPane.showMessageDialog(rootPane, "NO SE ENCONTRARON ALUMNOS", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultarCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultarCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultarCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultarCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConsultarCalificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1Consultar;
    private javax.swing.JButton boton2Salir;
    private javax.swing.JButton boton3Cancelar;
    private javax.swing.JComboBox cbox1Materia;
    private javax.swing.JComboBox cbox2Grado;
    private javax.swing.JComboBox cbox3Evaluacion;
    private javax.swing.JComboBox cbox4Grupo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jitem1;
    private javax.swing.JPanel jp1ConsultarCalificaciones;
    private javax.swing.JPanel jp2InformaciondeEvaluacion;
    private javax.swing.JPanel jp3Resultados;
    private javax.swing.JLabel lab1Materia;
    private javax.swing.JLabel lab2Grado;
    private javax.swing.JLabel lab3Grupo;
    private javax.swing.JLabel lab4Evaluacion;
    private javax.swing.JMenuBar menu1;
    private javax.swing.JTable table1Calificaciones;
    // End of variables declaration//GEN-END:variables
}
