/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteLogin;

import PaqueteMantenimientodeGrupos.InterfazRegistrarGrupo;
import PaqueteMantenimientodeGrupos.InterfazEliminarGrupo;
import PaqueteMantenimientodeGrupos.InterfazConsultadeGrupos;
import PaqueteMantenimientodeMaterias.InterfazRegistrarMateria;
import PaqueteMantenimientodeMaterias.InterfazEliminarMateria;
import PaqueteMantenimientodeMaterias.InterfazConsultadeMaterias;
import PaqueteMantenimientoUsuarios.InterfazConsultaEspecificaAlumno;
import PaqueteMantenimientoUsuarios.InterfazConsultaEspecificaMaestro;
import PaqueteMantenimientoUsuarios.InterfazConsultaGeneralAlumno;
import PaqueteMantenimientoUsuarios.InterfazConsultaGeneralMaestro;
import PaqueteMantenimientoUsuarios.InterfazEliminarAlumno;
import PaqueteMantenimientoUsuarios.InterfazEliminarMaestro;
import PaqueteMantenimientoUsuarios.InterfazModificarAlumno;
import PaqueteMantenimientoUsuarios.InterfazRegistrarAlumno;
import PaqueteMantenimientoUsuarios.InterfazRegistrarMaestro;
import PaqueteMantenimientoUsuarios.interfazmodificarmaestro;
import PaqueteMantenimientodeMaterias.InterfazModificarMateria;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author franciscoantonio
 */
public class InterfazPrincipalAdministrador extends javax.swing.JFrame {

    InterfazRegistrarMaestro registrarMaestro = new InterfazRegistrarMaestro();
    InterfazRegistrarAlumno registrarAlumno = new InterfazRegistrarAlumno();
    InterfazEliminarMaestro eliminarMaestro = new InterfazEliminarMaestro();
    InterfazEliminarAlumno eliminaraAlumno = new InterfazEliminarAlumno();
    interfazmodificarmaestro modificarMaestro = new interfazmodificarmaestro();
    InterfazModificarAlumno modificarAlumno = new InterfazModificarAlumno();
    InterfazConsultaGeneralMaestro consultaGeneralMaestro = new InterfazConsultaGeneralMaestro();
    InterfazConsultaGeneralAlumno consultaGeneralAlumno = new InterfazConsultaGeneralAlumno();
    InterfazConsultaEspecificaMaestro consultaEspecificaMestro = new InterfazConsultaEspecificaMaestro();
    InterfazConsultaEspecificaAlumno consultaEspecificaAlumno = new InterfazConsultaEspecificaAlumno();
    InterfazRegistrarGrupo altadeGrupo = new InterfazRegistrarGrupo();
    InterfazEliminarGrupo eliminarGrupo = new InterfazEliminarGrupo();
    InterfazConsultadeGrupos consultadeGrupos = new InterfazConsultadeGrupos();
    InterfazRegistrarMateria altadeMateria = new InterfazRegistrarMateria();
    InterfazEliminarMateria eliminarMateria = new InterfazEliminarMateria();
    InterfazConsultadeMaterias consultadeMaterias = new InterfazConsultadeMaterias();
    InterfazModificarMateria modificarMateria = new InterfazModificarMateria();

    /**
     * Creates new form InterfazPrincipalAdministrador
     */
    public InterfazPrincipalAdministrador() throws ClassNotFoundException, SQLException {

        initComponents();
        //establece la posicion central de la interfaz
        this.setLocationRelativeTo(null);

        //establecer la dimencion de la interfaz
        this.setMinimumSize(new Dimension(696, 483));

        //coloca el icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        //coloca el fondo en la interfaz
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/imagenes/fondo.png"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), u­no.getIconHeight());

        //des activa la opcion maximizar y cerrar
        this.setResizable(false);
        setDefaultCloseOperation(0);

        //asigna el nombre de administrador en la interfaz
        jMenu2.setText("Mi cuenta: ADMINISTRADOR");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jitem9 = new javax.swing.JMenuItem();
        jitem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jitem6 = new javax.swing.JMenuItem();
        jitem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jitem8 = new javax.swing.JMenuItem();
        jitem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jitem2 = new javax.swing.JMenuItem();
        jitem3 = new javax.swing.JMenuItem();
        jitem4 = new javax.swing.JMenuItem();
        jitem5 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jitem12 = new javax.swing.JMenuItem();
        jitem13 = new javax.swing.JMenuItem();
        jitem14 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jitem15 = new javax.swing.JMenuItem();
        jitem16 = new javax.swing.JMenuItem();
        jitem18 = new javax.swing.JMenuItem();
        jitem17 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jitem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InterfazPrincipalAdministrador");
        setMaximumSize(new java.awt.Dimension(696, 483));
        setMinimumSize(new java.awt.Dimension(696, 483));

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.jpg"))); // NOI18N
        jMenu1.setText("Menú");

        jMenu7.setText("Mantenimiento Usuarios");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alta de reactivo.png"))); // NOI18N
        jMenu4.setText("Registrar Usuario");

        jitem9.setText("Registrar maestro");
        jitem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMaestro(evt);
            }
        });
        jMenu4.add(jitem9);

        jitem11.setText("Registrar alumno");
        jitem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAlumno(evt);
            }
        });
        jMenu4.add(jitem11);

        jMenu7.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar reactivo.png"))); // NOI18N
        jMenu3.setText("Eliminar Usuario");

        jitem6.setText("Eliminar maestro");
        jitem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMaestro(evt);
            }
        });
        jMenu3.add(jitem6);

        jitem7.setText("Eliminar alumno");
        jitem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAlumno(evt);
            }
        });
        jMenu3.add(jitem7);

        jMenu7.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar reactivos.png"))); // NOI18N
        jMenu5.setText("Modificar Usuario");

        jitem8.setText("Modificar maestro");
        jitem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMaestro(evt);
            }
        });
        jMenu5.add(jitem8);

        jitem10.setText("Modificar alumno");
        jitem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAlumno(evt);
            }
        });
        jMenu5.add(jitem10);

        jMenu7.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta de reactivos.png"))); // NOI18N
        jMenu6.setText("Consultar Usuario");

        jitem2.setText("Consulta general maestro");
        jitem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaGMaestro(evt);
            }
        });
        jMenu6.add(jitem2);

        jitem3.setText("Consulta general alumno");
        jitem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaGAlumno(evt);
            }
        });
        jMenu6.add(jitem3);

        jitem4.setText("Consulta especifica maestro");
        jitem4.setToolTipText("");
        jitem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEMaestro(evt);
            }
        });
        jMenu6.add(jitem4);

        jitem5.setText("Consulta especifica alumno");
        jitem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEAlumno(evt);
            }
        });
        jMenu6.add(jitem5);

        jMenu7.add(jMenu6);

        jMenu1.add(jMenu7);

        jMenu8.setText("Mantenimiento Grupos");

        jitem12.setText("Registrar Grupo");
        jitem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarGrupo(evt);
            }
        });
        jMenu8.add(jitem12);

        jitem13.setText("Eliminar Grupo");
        jitem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarGrupo(evt);
            }
        });
        jMenu8.add(jitem13);

        jitem14.setText("Consulta de Grupos");
        jitem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultadeGrupos(evt);
            }
        });
        jMenu8.add(jitem14);

        jMenu1.add(jMenu8);

        jMenu9.setText("Mantenimiento Materias");

        jitem15.setText("Registrar Materia");
        jitem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMateria(evt);
            }
        });
        jMenu9.add(jitem15);

        jitem16.setText("Eliminar Materia");
        jitem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMateria(evt);
            }
        });
        jMenu9.add(jitem16);

        jitem18.setText("Modificar Materia");
        jitem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMateria(evt);
            }
        });
        jMenu9.add(jitem18);

        jitem17.setText("Consulta de Materias");
        jitem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultadeMaterias(evt);
            }
        });
        jMenu9.add(jitem17);

        jMenu1.add(jMenu9);

        menu1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu2.setText("Mi cuenta");
        jMenu2.setToolTipText("");

        jitem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar sesion.png"))); // NOI18N
        jitem1.setText("Cerrar sesión  ");
        jitem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesion(evt);
            }
        });
        jMenu2.add(jitem1);

        menu1.add(jMenu2);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarMaestro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMaestro
        registrarMaestro.setVisible(true);
    }//GEN-LAST:event_registrarMaestro

    private void registrarAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAlumno
        registrarAlumno.setVisible(true);
    }//GEN-LAST:event_registrarAlumno

    private void eliminarMaestro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMaestro
        eliminarMaestro.setVisible(true);
    }//GEN-LAST:event_eliminarMaestro

    private void eliminarAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAlumno
        eliminaraAlumno.setVisible(true);
    }//GEN-LAST:event_eliminarAlumno

    private void modificarMaestro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMaestro
        modificarMaestro.setVisible(true);
    }//GEN-LAST:event_modificarMaestro

    private void modificarAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAlumno
        modificarAlumno.setVisible(true);
    }//GEN-LAST:event_modificarAlumno

    private void consultaGMaestro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaGMaestro
        consultaGeneralMaestro.setVisible(true);
    }//GEN-LAST:event_consultaGMaestro

    private void consultaGAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaGAlumno
        consultaGeneralAlumno.setVisible(true);
    }//GEN-LAST:event_consultaGAlumno

    private void consultaEMaestro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEMaestro
        consultaEspecificaMestro.setVisible(true);
    }//GEN-LAST:event_consultaEMaestro

    private void consultaEAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEAlumno
        consultaEspecificaAlumno.setVisible(true);
    }//GEN-LAST:event_consultaEAlumno

    private void cerrarSesion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesion
        InterfazLogin login = new InterfazLogin();
        login.setVisible(true);
        this.setVisible(false);

        registrarMaestro.setVisible(false);
        registrarAlumno.setVisible(false);
        eliminarMaestro.setVisible(false);
        eliminaraAlumno.setVisible(false);
        modificarMaestro.setVisible(false);
        modificarAlumno.setVisible(false);
        consultaGeneralMaestro.setVisible(false);
        consultaGeneralAlumno.setVisible(false);
        consultaEspecificaMestro.setVisible(false);
        consultaEspecificaAlumno.setVisible(false);
        consultadeMaterias.setVisible(false);
        eliminarMateria.setVisible(false);
        altadeMateria.setVisible(false);
        consultadeGrupos.setVisible(false);
        altadeGrupo.setVisible(false);
        eliminarGrupo.setVisible(false);
        modificarMateria.setVisible(false);

    }//GEN-LAST:event_cerrarSesion

    private void eliminarGrupo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarGrupo
        // TODO add your handling code here:
        eliminarGrupo.setVisible(true);
    }//GEN-LAST:event_eliminarGrupo

    private void registrarGrupo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarGrupo
        // TODO add your handling code here:
        altadeGrupo.setVisible(true);
    }//GEN-LAST:event_registrarGrupo

    private void consultadeGrupos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultadeGrupos
        // TODO add your handling code here:
        consultadeGrupos.setVisible(true);
    }//GEN-LAST:event_consultadeGrupos

    private void registrarMateria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMateria
        // TODO add your handling code here:
        altadeMateria.setVisible(true);
    }//GEN-LAST:event_registrarMateria

    private void eliminarMateria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMateria
        // TODO add your handling code here:
        eliminarMateria.setVisible(true);
    }//GEN-LAST:event_eliminarMateria

    private void consultadeMaterias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultadeMaterias
        // TODO add your handling code here:
        consultadeMaterias.setVisible(true);
    }//GEN-LAST:event_consultadeMaterias

    private void modificarMateria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMateria
        // TODO add your handling code here:
        modificarMateria.setVisible(true);
    }//GEN-LAST:event_modificarMateria

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazPrincipalAdministrador().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(InterfazPrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jitem1;
    private javax.swing.JMenuItem jitem10;
    private javax.swing.JMenuItem jitem11;
    private javax.swing.JMenuItem jitem12;
    private javax.swing.JMenuItem jitem13;
    private javax.swing.JMenuItem jitem14;
    private javax.swing.JMenuItem jitem15;
    private javax.swing.JMenuItem jitem16;
    private javax.swing.JMenuItem jitem17;
    private javax.swing.JMenuItem jitem18;
    private javax.swing.JMenuItem jitem2;
    private javax.swing.JMenuItem jitem3;
    private javax.swing.JMenuItem jitem4;
    private javax.swing.JMenuItem jitem5;
    private javax.swing.JMenuItem jitem6;
    private javax.swing.JMenuItem jitem7;
    private javax.swing.JMenuItem jitem8;
    private javax.swing.JMenuItem jitem9;
    private javax.swing.JMenuBar menu1;
    // End of variables declaration//GEN-END:variables
}
