/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteLogin;

import PaqueteMantenimientodeEvaluaciones.InterfazIniciarEvaluacion;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazLogin extends javax.swing.JFrame {

    int idUsuario;
    String tipoUsuario;
    String nombre;
    int clic = 0;

    /**
     * Creates new form InterfazLoginn
     */
    public InterfazLogin() {
        initComponents();

        //limpia campo de contraseña
        pass1Contraseña.setText("");

        //establece la posicion central
        this.setLocationRelativeTo(null);

        //establecer la dimencion de la interfaz
        this.setMinimumSize(new Dimension(900, 700));

        //colocar icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        //colocar la imagen de fonde en la interfaz
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/imagenes/fondoo.png"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
        clic = 1;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab1Usuario = new javax.swing.JLabel();
        lab2Contraseña = new javax.swing.JLabel();
        txt1Usuario = new javax.swing.JTextField();
        boton1Ingresar = new javax.swing.JButton();
        pass1Contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setMinimumSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        lab1Usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab1Usuario.setForeground(new java.awt.Color(255, 255, 255));
        lab1Usuario.setText("Usuario:");

        lab2Contraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab2Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        lab2Contraseña.setText("Contraseña:");

        txt1Usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt1Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                compararTeclas(evt);
            }
        });

        boton1Ingresar.setBackground(new java.awt.Color(0, 0, 153));
        boton1Ingresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton1Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        boton1Ingresar.setText("Ingresar");
        boton1Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerdatosUsuario(evt);
            }
        });

        pass1Contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pass1Contraseña.setText("jPasswordField1");
        pass1Contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                compararTeclas(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(518, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab2Contraseña)
                    .addComponent(lab1Usuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton1Ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(txt1Usuario)
                    .addComponent(pass1Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab1Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass1Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(boton1Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
    }//GEN-LAST:event_jTextField2ActionPerformed

    //[2] consulta todos los datos de los usuarios registrados
    private void obtenerdatosUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerdatosUsuario

        if (txt1Usuario.getText().length() != 0 && pass1Contraseña.getText().length() != 0) {
            ControlUsuario usuario = new ControlUsuario();
            try {
                ResultSet resultado = usuario.consultarGeneral();
                comparardatosUsuario(resultado);

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InterfazLogin.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "NO DEJE CAMPOS VACIOS", "Error", JOptionPane.OK_OPTION);

        }

    }//GEN-LAST:event_obtenerdatosUsuario

    //[1] verifica si la tecla presionado fue ENTER
    // si es asi acciona el metodo de  boton1IngresarActionPerformed
    private void compararTeclas(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_compararTeclas
        if (evt.VK_ENTER == evt.getKeyCode()) {

            if (clic == 0) {
                java.awt.event.ActionEvent evento = null;
                obtenerdatosUsuario(evento);
                clic++;
            } else {
                clic = 0;
            }

        }

    }//GEN-LAST:event_compararTeclas

    //[3] comparan los datos ingresados con los obtenidos en la consulta
    // si coincide abre la interfaz correspondiente
    public void comparardatosUsuario(ResultSet resultado) throws SQLException, ClassNotFoundException {
        boolean usuarioCorrecto = false;

        while (resultado.next()) {
            if (txt1Usuario.getText().compareTo(resultado.getObject(3).toString()) == 0
                    && pass1Contraseña.getText().compareTo(resultado.getObject(4).toString()) == 0) {

                usuarioCorrecto = true;
                idUsuario = Integer.parseInt(resultado.getObject(1).toString());
                tipoUsuario = resultado.getObject(2).toString();
                ControlUsuario usuario = new ControlUsuario();

                txt1Usuario.setText("");
                pass1Contraseña.setText("");

                if (tipoUsuario.compareTo("ALUMNO") == 1) {
                    iniciarSesionAlumno(usuario);
                } else if (tipoUsuario.compareTo("MAESTRO") == 1) {
                    iniciarSesionMaestro(usuario);
                } else if (tipoUsuario.compareTo("ADMINISTRADOR") == 0) {
                    iniciarSesionAdministrador();
                }

            }

        }
        if (idUsuario == 0) {

            JOptionPane.showMessageDialog(rootPane, "USUARIO Y/O CONTRASEÑA ERRONEA", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
        System.out.println("nombre del usuario: " + nombre + " Id usuario: " + idUsuario);
    }

    public void iniciarSesionAdministrador() throws ClassNotFoundException, SQLException {
        nombre = "ADMINISTRADOR";
        InterfazPrincipalAdministrador principalAdministrador = new InterfazPrincipalAdministrador();
        this.setVisible(false);
        principalAdministrador.setVisible(true);
    }

    public void iniciarSesionAlumno(ControlUsuario usuario) throws ClassNotFoundException, SQLException {
        nombre = usuario.consultarNombreCompleto(idUsuario, tipoUsuario);
        InterfazIniciarEvaluacion iniciarEvaluacion = new InterfazIniciarEvaluacion();
        iniciarEvaluacion.idUsuario = idUsuario;
        iniciarEvaluacion.nombre = nombre;
        this.setVisible(false);
        iniciarEvaluacion.setVisible(true);
    }

    public void iniciarSesionMaestro(ControlUsuario usuario) throws ClassNotFoundException, SQLException {
        nombre = usuario.consultarNombreCompleto(idUsuario, tipoUsuario);
        InterfazPrincipalMaestro principal = new InterfazPrincipalMaestro();
        principal.idUsuario = idUsuario;
        principal.nombre = nombre;
        this.setVisible(false);
        principal.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLogin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1Ingresar;
    private javax.swing.JLabel lab1Usuario;
    private javax.swing.JLabel lab2Contraseña;
    private javax.swing.JPasswordField pass1Contraseña;
    private javax.swing.JTextField txt1Usuario;
    // End of variables declaration//GEN-END:variables
}
