/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteLogin;

import PaqueteCalificaciones.InterfazConsultarCalificaciones;
import PaqueteMantenimientodeEvaluaciones.InterfazAplicarEvaluacion;
import PaqueteMantenimientodeEvaluaciones.InterfazGenerarEvaluacion;
import PaqueteMantenimientodeEvaluaciones.InterfazModificarEvaluacion;
import PaqueteMantenimientodeReactivos.InterfazAltaDeReactivos;
import PaqueteMantenimientodeReactivos.InterfazConsultaDeReactivos;
import PaqueteMantenimientodeReactivos.InterfazEliminarReactivos;
import PaqueteMantenimientodeReactivos.InterfazModificarReactivos;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author FRANCISCO ZAVALA SILVA
 */
public class InterfazPrincipalMaestro extends javax.swing.JFrame {

    public int idUsuario;
    public String nombre;
    InterfazGenerarEvaluacion generarEvaluacion = new InterfazGenerarEvaluacion();
    InterfazConsultarCalificaciones consultarCalificaciones = new InterfazConsultarCalificaciones();
    InterfazAltaDeReactivos altaReactivo = new InterfazAltaDeReactivos();
    InterfazConsultaDeReactivos consultaReactivo = new InterfazConsultaDeReactivos();
    InterfazEliminarReactivos eliminarReactivo = new InterfazEliminarReactivos();
    InterfazModificarReactivos modificarReactivo = new InterfazModificarReactivos();
    InterfazAplicarEvaluacion aplicarEvaluacion = new InterfazAplicarEvaluacion();
    InterfazModificarEvaluacion modificarEvaluaciones = new InterfazModificarEvaluacion();

    /**
     * Creates new form Principal1
     */
    public InterfazPrincipalMaestro() {
        initComponents();
        //establece la posicion central
        this.setLocationRelativeTo(null);

        //establecer la dimencion 500,500
        this.setMinimumSize(new Dimension(500, 500));

        //establece el  icono en la interfaz
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        //coloca la imagen de fondo en la interfaz
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/imagenes/fondo.png"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), u­no.getIconHeight());

        //des activa la opcion maximizar 
        this.setResizable(false);
        //desactiva la opcion cerrar
        setDefaultCloseOperation(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jitem4 = new javax.swing.JMenuItem();
        jitem5 = new javax.swing.JMenuItem();
        menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jitem7 = new javax.swing.JMenuItem();
        jitem10 = new javax.swing.JMenuItem();
        jitem11 = new javax.swing.JMenuItem();
        jitem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jitem2 = new javax.swing.JMenuItem();
        jitem6 = new javax.swing.JMenuItem();
        jitem8 = new javax.swing.JMenuItem();
        jitem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jitem1 = new javax.swing.JMenuItem();

        jitem4.setText("jMenuItem2");

        jitem5.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Principal Maestro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                personalizarInterfaz(evt);
            }
        });

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.jpg"))); // NOI18N
        jMenu1.setText("Menú");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento de reactivos.png"))); // NOI18N
        jMenu4.setText("Mantenimiento de reactivos");

        jitem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alta de reactivo.png"))); // NOI18N
        jitem7.setText("Alta de reactivos");
        jitem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altadeReactivos(evt);
            }
        });
        jMenu4.add(jitem7);

        jitem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar reactivo.png"))); // NOI18N
        jitem10.setText("Eliminar reactivos");
        jitem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarReactivos(evt);
            }
        });
        jMenu4.add(jitem10);

        jitem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar reactivos.png"))); // NOI18N
        jitem11.setText("Modificar reactivos");
        jitem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarReactivos(evt);
            }
        });
        jMenu4.add(jitem11);

        jitem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consulta de reactivos.png"))); // NOI18N
        jitem9.setText("Consulta de reactivos");
        jitem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarReactivos(evt);
            }
        });
        jMenu4.add(jitem9);

        jMenu1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento de  evaluaciones.jpg"))); // NOI18N
        jMenu3.setText("Mantenimiento de evaluaciones");

        jitem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/generar evaluacion.png"))); // NOI18N
        jitem2.setText("Generar evaluación");
        jitem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarEvaluacion(evt);
            }
        });
        jMenu3.add(jitem2);

        jitem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aplicar evaluacion.png"))); // NOI18N
        jitem6.setText("Aplicar evaluación");
        jitem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarEvaluacion(evt);
            }
        });
        jMenu3.add(jitem6);

        jitem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar reactivos.png"))); // NOI18N
        jitem8.setText("Modificar evaluación");
        jitem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEvaluacion(evt);
            }
        });
        jMenu3.add(jitem8);

        jMenu1.add(jMenu3);

        jitem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar calificaciones.png"))); // NOI18N
        jitem3.setText("Consultar calificaciones");
        jitem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCalificaciones(evt);
            }
        });
        jMenu1.add(jitem3);

        menu1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mi cuenta.png"))); // NOI18N
        jMenu2.setText("Mi cuenta");
        jMenu2.setToolTipText("");

        jitem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar sesion.png"))); // NOI18N
        jitem1.setText("Cerrar sesión  ");
        jitem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesion(evt);
            }
        });
        jMenu2.add(jitem1);

        menu1.add(jMenu2);

        setJMenuBar(menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //cierra completamente la aplicacion asi como las interfaces abiertas
    private void cerrarSesion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesion
        // TODO add your handling code here:
        int salir = JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA SALIR?");
        if (salir == 0) {
            InterfazLogin login = new InterfazLogin();
            login.setVisible(true);
            this.setVisible(false);
            generarEvaluacion.setVisible(false);
            consultarCalificaciones.setVisible(false);
            altaReactivo.setVisible(false);
            consultaReactivo.setVisible(false);
            eliminarReactivo.setVisible(false);
            modificarReactivo.setVisible(false);
            aplicarEvaluacion.setVisible(false);
            modificarEvaluaciones.setVisible(false);

        }


    }//GEN-LAST:event_cerrarSesion

    //abre la interfaz generarEvaluacion
    private void generarEvaluacion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarEvaluacion

        generarEvaluacion.idUsuario = idUsuario;
        generarEvaluacion.nombre = nombre;
        generarEvaluacion.setVisible(true);

    }//GEN-LAST:event_generarEvaluacion

    //abre la interfaz aplicarEvaluacion
    private void aplicarEvaluacion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarEvaluacion

        aplicarEvaluacion.idUsuario = idUsuario;
        aplicarEvaluacion.nombre = nombre;
        aplicarEvaluacion.setVisible(true);
    }//GEN-LAST:event_aplicarEvaluacion

    //abre la interfaz consultarCalificaciones
    private void consultarCalificaciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCalificaciones

        consultarCalificaciones.idUsuario = idUsuario;
        consultarCalificaciones.nombreUsuario = nombre;
        consultarCalificaciones.setVisible(true);
    }//GEN-LAST:event_consultarCalificaciones

    //abre la interfaz altaReactivo
    private void altadeReactivos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altadeReactivos

        altaReactivo.idUsuario = idUsuario;
        altaReactivo.nombre = nombre;
        altaReactivo.setVisible(true);
    }//GEN-LAST:event_altadeReactivos

    //abre la interfaz consultaReactivo
    private void consultarReactivos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarReactivos

        consultaReactivo.idUsuario = idUsuario;
        consultaReactivo.nombre = nombre;
        consultaReactivo.setVisible(true);
    }//GEN-LAST:event_consultarReactivos

    //abre la interfaz eliminarReactivo
    private void eliminarReactivos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarReactivos

        eliminarReactivo.idUsuario = idUsuario;
        eliminarReactivo.nombre = nombre;
        eliminarReactivo.setVisible(true);
    }//GEN-LAST:event_eliminarReactivos

    //abre la interfaz modificarReactivo
    private void modificarReactivos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarReactivos

        modificarReactivo.idUsuario = idUsuario;
        modificarReactivo.nombre = nombre;
        modificarReactivo.setVisible(true);
    }//GEN-LAST:event_modificarReactivos

    //asigna el nombre y el id del usuario a la intefaz
    private void personalizarInterfaz(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_personalizarInterfaz

        jMenu2.setText("Mi cuenta: " + nombre + " : " + idUsuario);
    }//GEN-LAST:event_personalizarInterfaz

    //abre la interfaz modificarEvaluaciones
    private void modificarEvaluacion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEvaluacion

        modificarEvaluaciones.idUsuario = idUsuario;
        modificarEvaluaciones.nombre = nombre;
        modificarEvaluaciones.setVisible(true);
    }//GEN-LAST:event_modificarEvaluacion

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipalMaestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jitem1;
    private javax.swing.JMenuItem jitem10;
    private javax.swing.JMenuItem jitem11;
    private javax.swing.JMenuItem jitem2;
    private javax.swing.JMenuItem jitem3;
    private javax.swing.JMenuItem jitem4;
    private javax.swing.JMenuItem jitem5;
    private javax.swing.JMenuItem jitem6;
    private javax.swing.JMenuItem jitem7;
    private javax.swing.JMenuItem jitem8;
    private javax.swing.JMenuItem jitem9;
    private javax.swing.JMenuBar menu1;
    // End of variables declaration//GEN-END:variables
}
